Repository puma/puma, pull requests merged in 2019-02, with the labels that each got.

#1508 Fix 3 corner cases when request body is chunked
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: bug

#1514 restart.md: Added note about JRuby and Windows
  docs/restart.md
Labels: docs, waiting/blocked

#1562 add support for disabling TLSv1.0
  README.md
  ext/puma_http11/mini_ssl.c
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  lib/puma/binder.rb
  lib/puma/dsl.rb
  lib/puma/minissl.rb
  test/test_binder.rb
Labels: feature, important!
