Repository puma/puma, pull requests merged in 2019-08, with the labels that each got.

#1816 Allow to define a custom formatter for logs
  History.md
  lib/puma/dsl.rb
  lib/puma/launcher.rb
  test/config/custom_log_formatter.rb
  test/test_cli.rb
Labels: feature

#1822 Swallow connection errors when sending early hints
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: feature

#1844 Instrument start time
  History.md
  lib/puma/cluster.rb
  lib/puma/runner.rb
  lib/puma/single.rb
  test/test_cli.rb
Labels: feature

#1857 Avoid blocking on SSL's `#read_nonblock`
  lib/puma/minissl.rb
  test/test_puma_server_ssl.rb
Labels: bug

#1812 Fix a bug that the last CRLF of chunked body may be used in the next request
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: bug

#1863 Remove debug backtrace from pumactl
  lib/puma/control_cli.rb
Labels: feature

#1836 Openssl updates
  .travis.yml
  ext/puma_http11/mini_ssl.c
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  lib/puma/binder.rb
  lib/puma/dsl.rb
  lib/puma/minissl.rb
  test/test_binder.rb
  test/test_config.rb
  test/test_puma_server_ssl.rb
Labels: feature, ssl

#1887 cluster.rb - no zombies
  .travis.yml
  lib/puma/cluster.rb
  test/test_integration.rb
Labels: bug

#1885 Check puma config environment file on control_cli
  lib/puma/control_cli.rb
  test/test_pumactl.rb
Labels: feature

#1924 test_integration.erb - fix intermittent test
  test/test_integration.rb
Labels: bug

#1908 Fixes Cluster worker shutdown/restart
  lib/puma/cluster.rb
  test/test_integration.rb
Labels: bug, restart, waiting/blocked

#1934 Allow semicolon in url-path
  ext/puma_http11/http11_parser.c
  ext/puma_http11/http11_parser_common.rl
  test/test_http11.rb
Labels: feature
