Repository puma/puma, pull requests merged in 2019-10, with the labels that each got.

#2006 Binder fixes for 4.2.1
  lib/puma/binder.rb
  test/test_binder.rb
Labels: bug

#2000 Remove Puma::Delegation [changelog skip]
  lib/puma/client.rb
  lib/puma/delegation.rb
  lib/puma/server.rb
Labels: maintenance

#2011 Allow for symbols to be used in verify_mode
  History.md
  lib/puma/dsl.rb
  test/test_config.rb
Labels: bug, ssl

#2010 Strip header whitespace. Fix #1890. Code by @matthewd
  History.md
  ext/puma_http11/org/jruby/puma/Http11.java
  ext/puma_http11/puma_http11.c
  test/test_http11.rb
Labels: c-ext, feature, jruby

#2016 this line gets overwritten when the YAML is parsed so we should removed [changelog skip]
  .travis.yml
Labels: maintenance

#2035 Update pumactl to remove development as default environment
  History.md
  lib/puma/control_cli.rb
  test/helpers/config_file.rb
  test/test_config.rb
  test/test_pumactl.rb
Labels: bug

#2039 Remove broken puma/convenient [changelog skip]
  lib/puma/convenient.rb
Labels: bug

#2045 [README] Add section about TCP mode [changelog skip]
  docs/tcp_mode.md
Labels: docs

#2046 Add SSL support for the control app
  History.md
  lib/puma/binder.rb
  lib/puma/minissl/context_builder.rb
  lib/puma/runner.rb
  test/helpers/ssl.rb
  test/test_binder.rb
  test/test_cli.rb
Labels: feature

#2050 Fix typo "c" -> "user_config" for --extra_runtime_dependencies
  History.md
  lib/puma/cli.rb
  test/test_cli.rb
Labels: bug

#2059 add missing require in spec
  test/test_pumactl.rb
Labels: maintenance
