Repository puma/puma, pull requests merged in 2019-07, with the labels that each got.

#1832 Use OpenSSL DTLS_method & TLS_server_method when available
  .travis.yml
  History.md
  Rakefile
  ext/puma_http11/extconf.rb
  ext/puma_http11/mini_ssl.c
Labels: bug, important!

#1829 fix #1775
  History.md
  lib/puma/binder.rb
  test/test_integration.rb
Labels: bug, important!

#1838 Avoid casting worker_timeout twice
  lib/puma/dsl.rb
Labels: feature

#1846 Test cleanup and parallelization
  lib/puma.rb
  lib/puma/accept_nonblock.rb
  lib/puma/app/status.rb
  lib/puma/plugin/tmp_restart.rb
  lib/puma/rack/builder.rb
  lib/puma/rack/urlmap.rb
  lib/puma/rack_default.rb
  lib/rack/handler/puma.rb
  test/helper.rb
  test/test_app_status.rb
  test/test_binder.rb
  test/test_integration.rb
Labels: feature

#1491 RACK_URL_SCHEME calculation caring about more headers
  lib/puma/const.rb
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: bug

#1837 Avoid mutating global STDOUT & STDERR
  lib/puma/events.rb
  test/test_events.rb
  test/test_tcp_logger.rb
Labels: feature

#1831 Add REQUEST_PATH on parse error message
  lib/puma/events.rb
  test/test_events.rb
Labels: feature
