Repository puma/puma, pull requests merged in 2019-09, with the labels that each got.

#1946 Revert "Avoid mutating global STDOUT & STDERR (#1837)"
  lib/puma/events.rb
  test/test_events.rb
  test/test_tcp_logger.rb
Labels: bug

#1105 Allow extra runtime deps to be defined when using prune_bundler
  lib/puma/cli.rb
  lib/puma/dsl.rb
  lib/puma/launcher.rb
  test/config/prune_bundler_with_deps.rb
  test/rackup/hello-last-load-path.ru
  test/test_integration.rb
  test/test_launcher.rb
Labels: feature, restart

#1958 Privatize binder listeners
  lib/puma/binder.rb
  lib/puma/launcher.rb
  test/test_binder.rb
Labels: feature

#1786 Report tcp 0 port properly. Fixes #1679
  lib/puma/binder.rb
  test/test_binder.rb
Labels: bug, waiting/blocked

#1961 Remove unnecessary SIGINT trap for Jruby
  lib/puma/launcher.rb
  test/test_integration_single.rb
Labels: bug

#1968 All Puma threads are named
  lib/puma.rb
  lib/puma/cluster.rb
  lib/puma/launcher.rb
  lib/puma/plugin.rb
  lib/puma/reactor.rb
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/test_integration_cluster.rb
  test/test_thread_pool.rb
Labels: feature

#1970 unlink UNIXSocket files, fix Binder#close
  lib/puma/binder.rb
  lib/puma/cluster.rb
  lib/puma/launcher.rb
  lib/puma/single.rb
Labels: bug

#1952 Fix Worker external TERM signalling
  lib/puma/cluster.rb
Labels: bug

#1977 Remove jruby-stable from list of allowed failures
  .travis.yml
Labels: bug

#1965 Update test_integration files per PR #1956
  lib/puma/cluster.rb
  test/config/worker_shutdown_timeout_2.rb
  test/helper.rb
  test/helpers/integration.rb
  test/rackup/sleep_pid.ru
  test/rackup/sleep_step.ru
  test/test_cli.rb
  test/test_integration_cluster.rb
  test/test_integration_pumactl.rb
  test/test_integration_single.rb
Labels: waiting/blocked

#1918 Try Github Actions
  .github/workflows/ruby.yml
  .travis.yml
  README.md
  appveyor.yml
  test/helper.rb
Labels: feature

#1974 4.2.0
  History.md
  lib/puma/const.rb
Labels: important!
