Repository puma/puma, pull requests merged in 2020-07, with the labels that each got.

#2300 WIP Log binding on http:// for TCP bindings to make it clickable
  History.md
  lib/puma/binder.rb
  test/test_binder.rb
Labels: feature

#2312 Improve worker shutdown reliability, CI fixes
  History.md
  lib/puma/events.rb
  lib/puma/server.rb
  test/helper.rb
  test/test_integration_cluster.rb
Labels: maintenance

#2324 [changelog skip] [ci skip] Clarify how to run puma in single mode
  docs/deployment.md
Labels: docs
