Repository puma/puma, pull requests merged in 2020-03, with the labels that each got.

#2112 Refactor listener closing code
  History.md
  lib/puma/binder.rb
  lib/puma/launcher.rb
  lib/puma/runner.rb
  test/test_binder.rb
  test/test_integration_pumactl.rb
Labels: bug, waiting-for-review

#2151 Use with_unbundled_env for Bundler 2.1+
  lib/puma/launcher.rb
Labels: maintenance

#2156 Binder testcov
  lib/puma/binder.rb
  test/test_binder.rb
Labels: maintenance

#2160 New binder tests
  lib/puma/binder.rb
  lib/puma/launcher.rb
  test/test_binder.rb
Labels: maintenance

#2161 Suppress Rack deprecation warning in specs [changelog skip]
  test/test_config.rb
Labels: maintenance

#2162 Show RUBYOPT in test 'header', use setup-ruby-pkgs in Actions CI [changelog skip]
  .github/workflows/ruby.yml
  test/test_puma_server_ssl.rb
Labels: maintenance

#2169 Remove TCP mode
  History.md
  docs/tcp_mode.md
  lib/puma/cli.rb
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/runner.rb
  lib/puma/server.rb
  lib/puma/tcp_logger.rb
  test/test_tcp_logger.rb
  test/test_tcp_rack.rb
Labels: maintenance

#2168 Increase max URI path length to 8196, closes #2134
  History.md
  ext/puma_http11/org/jruby/puma/Http11.java
  ext/puma_http11/puma_http11.c
  test/test_http11.rb
Labels: feature, waiting-for-review

#2155 Catch exceptions in hooks defined by users
  History.md
  lib/puma/cluster.rb
  lib/puma/configuration.rb
  lib/puma/launcher.rb
  test/test_config.rb
Labels: feature, waiting-for-review

#2154 Leave BUNDLE_GEMFILE unset in workers if it was unset in the master
  History.md
  lib/puma/launcher.rb
  test/bundle_preservation_test/version1/Gemfile
  test/bundle_preservation_test/version1/config.ru
  test/bundle_preservation_test/version1/config/puma.rb
  test/bundle_preservation_test/version2/Gemfile
  test/bundle_preservation_test/version2/config.ru
  test/bundle_preservation_test/version2/config/puma.rb
  test/test_preserve_bundler_env.rb
Labels: waiting-for-review

#2170 Remove daemonization
  History.md
  README.md
  docs/deployment.md
  docs/jungle/README.md
  docs/jungle/rc.d/README.md
  docs/jungle/rc.d/puma
  docs/jungle/rc.d/puma.conf
  docs/jungle/upstart/README.md
  docs/jungle/upstart/puma-manager.conf
  docs/jungle/upstart/puma.conf
  docs/systemd.md
  lib/puma/cli.rb
  lib/puma/cluster.rb
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/jruby_restart.rb
  lib/puma/launcher.rb
  lib/puma/rack/builder.rb
  lib/puma/runner.rb
  lib/puma/single.rb
  test/shell/t2.rb
  test/shell/t2_conf.rb
  tools/Dockerfile
  tools/jungle/README.md
  tools/jungle/init.d/README.md
  tools/jungle/init.d/puma
  tools/jungle/init.d/run-puma
Labels: maintenance

#2165 [changelog skip] Backfill tests for stdout/stderr redirection on SIGHUP
  test/test_redirect_io.rb
Labels: maintenance, waiting-for-changes

#2176 Socket activation tests
  lib/puma/binder.rb
  lib/puma/launcher.rb
  test/test_binder.rb
Labels: maintenance

#2187 Fix warnings for !HAS_FORK [changelog skip]
  test/test_preserve_bundler_env.rb
  test/test_puma_server_ssl.rb
Labels: maintenance

#2185 Actions - Add nonMRI workflow - allow failure - JRuby, TruffleRuby [changelog skip]
  .github/workflows/ruby.yml
  .travis.yml
  ext/puma_http11/extconf.rb
  lib/puma/minissl.rb
  test/shell/t1.rb
  test/shell/t2.rb
Labels: maintenance

#2195 Use SIGWINCH to print thread backtraces
  History.md
  docs/signals.md
  lib/puma/launcher.rb
  test/test_integration_cluster.rb
Labels: feature

#2198 Run tests on TruffleRuby, all tests pass now
  .github/workflows/ruby.yml
  History.md
  lib/puma/minissl.rb
  test/helper.rb
  test/shell/run.rb
  test/shell/t1.rb
  test/shell/t2.rb
  test/shell/t3.rb
  test/test_integration_pumactl.rb
  test/test_redirect_io.rb
  test/test_thread_pool.rb
Labels: maintenance

#2203 Handle thread shutdown responses via low level error messages
  History.md
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: feature, waiting-for-changes
