Repository puma/puma, pull requests merged in 2020-02, with the labels that each got.

#2102 Simplify random_token and remove insecure fallback
  History.md
  lib/puma/configuration.rb
Labels: maintenance

#2105 [changelog skip][ci skip] Add puma-status to the community extensions
  README.md
Labels: docs

#2103 Update Actions ruby.yml [changelog skip]
  .github/workflows/ruby.yml
  .travis.yml
Labels: maintenance

#2106 Instrument requests count
  History.md
  lib/puma/cluster.rb
  lib/puma/server.rb
  lib/puma/single.rb
  test/test_cli.rb
  test/test_web_server.rb
Labels: feature

#2114 Split ruby.yml, revise Actions, all OS's test from 2.3 thru master/head [changelog skip]
  .github/workflows/ruby.yml
Labels: maintenance

#1893 Preserve BUNDLE_GEMFILE and add a test for it
  History.md
  lib/puma/launcher.rb
  test/bundle_preservation_test/.gitignore
  test/bundle_preservation_test/Gemfile.bundle_env_preservation_test
  test/bundle_preservation_test/config.ru
  test/helpers/integration.rb
  test/test_preserve_bundler_env.rb
Labels: feature, waiting/blocked

#2075 remove setting quiet requests inside puma rack handler
  History.md
  lib/rack/handler/puma.rb
  test/test_rack_handler.rb
Labels: feature

#2118 puma.gemspec metadata["msys2_mingw_dependencies"] [changelog skip]
  puma.gemspec
Labels: maintenance

#2119 Send 408 request timeout even when queue requests is disabled
  History.md
  lib/puma/client.rb
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: bug

#2111 Simplify Runner#start_control URL parsing
  History.md
  lib/puma/binder.rb
  lib/puma/runner.rb
Labels: maintenance

#2121 Rescue IO::WaitReadable instead of EAGAIN for blocking read
  History.md
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: bug

#2076 Removes connected_port, implements connected_ports
  lib/puma/binder.rb
  lib/puma/launcher.rb
  lib/puma/minissl.rb
  lib/puma/server.rb
  test/test_cli.rb
  test/test_events.rb
  test/test_puma_server.rb
  test/test_puma_server_ssl.rb
  test/test_rack_handler.rb
  test/test_rack_server.rb
  test/test_web_server.rb
Labels: maintenance, waiting-for-review

#1980 IOBuffer back to Ruby
  History.md
  ext/puma_http11/PumaHttp11Service.java
  ext/puma_http11/io_buffer.c
  ext/puma_http11/org/jruby/puma/IOBuffer.java
  ext/puma_http11/puma_http11.c
  lib/puma/io_buffer.rb
  lib/puma/server.rb
  test/test_iobuffer.rb
Labels: maintenance, perf, waiting-for-changes

#2136 HTTP Injection - fix bug + 1 more vectors
  History.md
  lib/puma/const.rb
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: bug
