Repository puma/puma, pull requests merged in 2020-08, with the labels that each got.

#2345 Detect linux properly across all Ruby impls
  lib/puma/server.rb
Labels: feature, jruby

#2346 [changelog skip] Move integration logging test to main test suite
  test/config/t2_conf.rb
  test/shell/run.rb
  test/shell/t2.rb
  test/shell/t2_conf.rb
  test/test_integration_single.rb
Labels: maintenance

#2269 Load JSON at runtime
  History.md
  lib/puma.rb
  lib/puma/app/status.rb
  lib/puma/cluster.rb
Labels: bug, important!, waiting-for-changes

#2314 Explicitly include ctype.h to fix compilation warning
  History.md
  ext/puma_http11/puma_http11.c
Labels: bug, important!, waiting-for-review
