Repository puma/puma, pull requests merged in 2020-10, with the labels that each got.

#2405 Consolidate fast_write calls in Server, extract early_hints assembly
  History.md
  lib/puma/server.rb
Labels: maintenance, waiting-for-review

#2411 Adjust Actions workflows for new syntax [changelog skip]
  .github/workflows/mri.yml
  .github/workflows/non_mri.yml
Labels: maintenance

#2412 client.rb - remove JRuby specific 'finish' code
  History.md
  lib/puma/client.rb
Labels: maintenance

#2279 Reactor refactor
  History.md
  lib/puma/client.rb
  lib/puma/queue_close.rb
  lib/puma/reactor.rb
  lib/puma/server.rb
Labels: maintenance, waiting-for-review

#2419 Extract req/resp methods to new request.rb from server.rb
  History.md
  lib/puma/request.rb
  lib/puma/server.rb
Labels: maintenance, waiting-for-changes

#2423 Add hot_restart_does_not_drop_connections tests [changelog skip]
  test/helpers/integration.rb
  test/rackup/hello_with_delay.ru
  test/test_integration_cluster.rb
  test/test_integration_pumactl.rb
  test/test_integration_single.rb
Labels: maintenance, waiting-for-changes

#2429 Add test_client_quick_close_no_lowlevel_error_handler_call [changelog skip]
  test/test_puma_server.rb
Labels: maintenance

#2431 Fire on_booted after server starts
  History.md
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/single.rb
  test/test_cli.rb
Labels: bug, maintenance

#2430 ext_help.h, minissl.c, puma_http11.c - change macros Data_ -> TypedData_ [changelog skip]
  ext/puma_http11/ext_help.h
  ext/puma_http11/mini_ssl.c
  ext/puma_http11/puma_http11.c
Labels: c-ext, maintenance

#2434 Updates for non MRI CI stablity [changelog skip]
  .github/workflows/mri.yml
  .github/workflows/non_mri.yml
  test/helper.rb
  test/test_integration_single.rb
  test/test_launcher.rb
  test/test_out_of_band_server.rb
  test/test_persistent.rb
  test/test_puma_server.rb
Labels: maintenance

#2406 Adds configuration option to set max_fast_inline
  History.md
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/server.rb
  test/config/with_float_convert.rb
  test/test_config.rb
Labels: feature, waiting-for-changes

#2435 Server run thread safety fix [changelog skip]
  lib/puma/server.rb
  lib/puma/single.rb
  test/test_puma_server.rb
Labels: jruby, maintenance

#2427 Fix Bundler::GemNotFound errors for nio4r gem
  History.md
  bin/puma-wild
  lib/puma/launcher.rb
  lib/puma/reactor.rb
  test/config/prune_bundler_with_deps.rb
  test/rackup/hello-last-load-path.ru
  test/test_integration_cluster.rb
  test/test_launcher.rb
Labels: bug, waiting-for-review

#2413 Add test case for response header [changelog skip]
  test/test_response_header.rb
Labels: bug, maintenance, waiting-for-review

#2436 Add integration test to help prevent JSON loading regressions [changelog skip]
  test/config/prune_bundler_print_json_defined.rb
  test/test_integration_cluster.rb
Labels: bug, maintenance

#2442 Fix hang on shutdown in test_refork [changelog skip]
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  test/test_puma_server.rb
Labels: bug, maintenance, waiting-for-review

#2441 Fix-up test_refork, hot_restart_does_not_drop_connections [changelog skip]
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_integration_pumactl.rb
  test/test_pumactl.rb
Labels: maintenance, waiting-for-review

#2432 Add Client#io_ok?, check before Reactor#register
  History.md
  lib/puma/client.rb
  lib/puma/reactor.rb
Labels: bug

#2450 Refactor status.rb - dry it up a bit [changelog skip]
  lib/puma/app/status.rb
Labels: refactor

#2448 Remove accept_nonblock.rb, add test_integration_ssl.rb
  History.md
  lib/puma/accept_nonblock.rb
  lib/puma/binder.rb
  test/test_integration_ssl.rb
Labels: maintenance, waiting-for-changes

#2439 Ignore illegal response header
  History.md
  lib/puma/const.rb
  lib/puma/request.rb
  test/test_response_header.rb
Labels: bug, perf

#2438 Add systemd notify and watchdog support
  Gemfile
  History.md
  docs/systemd.md
  lib/puma/events.rb
  lib/puma/launcher.rb
  lib/puma/systemd.rb
  test/test_integration_systemd.rb
Labels: feature, systemd

#2460 Close idle connections immediately on shutdown
  History.md
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: feature

#2461 Pass preloaded application into new workers if available
  History.md
  lib/puma/cluster.rb
  test/rackup/write_to_stdout_on_boot.ru
  test/test_integration_cluster.rb
Labels: bug

#2451 Refactor control_cli.rb - add CMD_PATH_SIG_MAP [changelog skip]
  lib/puma/control_cli.rb
  test/test_pumactl.rb
Labels: refactor, waiting-for-review

#2449 cluster.rb - rearrange SIGURG & fork_worker code, small test fix [changelog skip]
  lib/puma/cluster.rb
  test/test_integration_cluster.rb
Labels: maintenance, waiting-for-review
