Repository puma/puma, pull requests merged in 2020-09, with the labels that each got.

#2317 JRuby - Add Puma::MiniSSL::Engine#init? and #teardown methods, run all SSL tests
  History.md
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  lib/puma/minissl.rb
  test/test_puma_server_ssl.rb
Labels: maintenance, waiting-for-review

#2323 Fix recursive `prune_bundler`
  History.md
  lib/puma/launcher.rb
  test/config/prune_bundler_with_multiple_workers.rb
  test/test_integration_cluster.rb
  test/test_integration_pumactl.rb
Labels: bug, important!, waiting-for-review

#2332 Do not quite when `pumactl` unexpectedly exits.
  test/test_pumactl.rb
Labels: bug, important!, maintenance, waiting-for-review

#2350 replace SOL_TCP with IPPROTO_TCP [changelog skip]
  lib/puma/server.rb
Labels: bug, maintenance

#2347 [changelog skip] Move integration logging test to main test suite
  Rakefile
  test/config/t3_conf.rb
  test/shell/run.rb
  test/shell/t3.rb
  test/test_integration_cluster.rb
Labels: maintenance, waiting-for-review

#2318 Test fixups, port 0 and timeout handling [changelog skip]
  test/helper.rb
  test/helpers/integration.rb
  test/test_busy_worker.rb
  test/test_events.rb
  test/test_integration_cluster.rb
  test/test_out_of_band_server.rb
  test/test_persistent.rb
  test/test_puma_server.rb
  test/test_puma_server_ssl.rb
  test/test_rack_server.rb
  test/test_web_server.rb
Labels: maintenance, waiting-for-review

#2306 Use Tempfile for sockets and state files in tests
  test/helpers/integration.rb
  test/helpers/tmp_path.rb
  test/test_binder.rb
  test/test_cli.rb
  test/test_integration_pumactl.rb
  test/test_launcher.rb
  test/test_rack_server.rb
  test/test_unix_socket.rb
Labels: maintenance, waiting-for-changes

#2302 Move initialization of KeyManagerFactory, TrustManagerFactory to server
  History.md
  ext/puma_http11/org/jruby/puma/MiniSSL.java
Labels: jruby, ssl, waiting-for-review

#2333 Update Actions, test certs, test code [changelog skip]
  .github/workflows/puma.yml
  examples/puma/cert_puma.pem
  examples/puma/client-certs/ca.crt
  examples/puma/client-certs/ca.key
  examples/puma/client-certs/client.crt
  examples/puma/client-certs/client.key
  examples/puma/client-certs/client_expired.crt
  examples/puma/client-certs/client_expired.key
  examples/puma/client-certs/client_unknown.crt
  examples/puma/client-certs/client_unknown.key
  examples/puma/client-certs/generate.rb
  examples/puma/client-certs/generate_client_test.rb
  examples/puma/client-certs/keystore.jks
  examples/puma/client-certs/run_server_with_certs.rb
  examples/puma/client-certs/server.crt
  examples/puma/client-certs/server.key
  examples/puma/client-certs/server.p12
  examples/puma/client-certs/unknown_ca.crt
  examples/puma/client-certs/unknown_ca.key
  examples/puma/generate_server_test.rb
  examples/puma/keystore.jks
  examples/puma/puma_keypair.pem
  examples/puma/server.p12
  test/helpers/ssl.rb
  test/test_puma_server_ssl.rb
Labels: maintenance, waiting-for-changes

#2358 Small test fixes - helpers/tmp_path.rb, helper.rb & test_redirect_io.rb [changelog skip]
  lib/puma/const.rb
  test/helper.rb
  test/helpers/integration.rb
  test/helpers/tmp_path.rb
  test/test_integration_cluster.rb
  test/test_integration_pumactl.rb
  test/test_redirect_io.rb
Labels: maintenance, waiting-for-changes

#2364 TestPumaServerSSLClient - share Context [changelog skip]
  test/test_puma_server_ssl.rb
Labels: maintenance

#2365 test/helper.rb -TimeoutEveryTestCase - set all timeouts to 45 sec [changelog skip]
  test/helper.rb
Labels: maintenance

#2305 Allow Puma to compile when built without SSL, load SSL files on demand
  .github/workflows/puma-no-ssl.yml
  History.md
  README.md
  Rakefile
  ext/puma_http11/no_ssl/PumaHttp11Service.java
  ext/puma_http11/puma_http11.c
  lib/puma.rb
  lib/puma/binder.rb
  lib/puma/detect.rb
  lib/puma/minissl.rb
  lib/puma/minissl/context_builder.rb
  lib/puma/reactor.rb
  lib/puma/runner.rb
  lib/puma/server.rb
  test/test_binder.rb
  test/test_cli.rb
  test/test_config.rb
  test/test_minissl.rb
  test/test_puma_server_ssl.rb
  test/test_pumactl.rb
Labels: bug, maintenance, waiting-for-changes

#2372 split TCP_CORK and TCP_INFO [changelog skip]
  lib/puma/server.rb
Labels: maintenance, waiting-for-review

#2376 [changelog skip] Fix error backtrace debug logging && Don't log not parsed request
  lib/puma/error_logger.rb
  test/test_error_logger.rb
Labels: maintenance, waiting-for-review

#2373 Consolidate option handling in Server, Server small refactors, doc changes
  History.md
  lib/puma/runner.rb
  lib/puma/server.rb
  test/test_busy_worker.rb
  test/test_integration_pumactl.rb
  test/test_out_of_band_server.rb
  test/test_persistent.rb
  test/test_puma_server.rb
  test/test_pumactl.rb
Labels: docs, maintenance, waiting-for-review

#2375 Change Events#ssl_error signature from (error, peeraddr, peercert) to (error, ssl_socket)
  History.md
  lib/puma/events.rb
  lib/puma/reactor.rb
  lib/puma/server.rb
  test/test_events.rb
  test/test_puma_server_ssl.rb
Labels: maintenance, waiting-for-review

#2380 Updates to 4.3.6 to pass CI, adds Ubuntu 20.04 [changelog skip]
  .github/workflows/puma.yml
  .github/workflows/ruby.yml
  examples/puma/cert_puma.pem
  examples/puma/client-certs/ca.crt
  examples/puma/client-certs/ca.key
  examples/puma/client-certs/client.crt
  examples/puma/client-certs/client.key
  examples/puma/client-certs/client_expired.crt
  examples/puma/client-certs/client_expired.key
  examples/puma/client-certs/client_unknown.crt
  examples/puma/client-certs/client_unknown.key
  examples/puma/client-certs/generate.rb
  examples/puma/client-certs/generate_client_test.rb
  examples/puma/client-certs/run_server_with_certs.rb
  examples/puma/client-certs/server.crt
  examples/puma/client-certs/server.key
  examples/puma/client-certs/unknown_ca.crt
  examples/puma/client-certs/unknown_ca.key
  examples/puma/generate_server_test.rb
  examples/puma/puma_keypair.pem
  examples/puma/server.p12
  ext/puma_http11/extconf.rb
  lib/puma/client.rb
  lib/puma/server.rb
  test/helpers/ssl.rb
  test/test_puma_server_ssl.rb
Labels: maintenance, waiting-for-review

#2271 Better error handling during force shutdown
  History.md
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/test_puma_server.rb
  test/test_thread_pool.rb
Labels: maintenance, waiting-for-review

#2381 Fix LoadError in CentOS 8 - 'require_relative' should not be necessar…
  History.md
  lib/puma.rb
Labels: bug, waiting-for-changes

#2387 Clean up tests [changelog skip]
  test/test_integration_cluster.rb
  test/test_integration_single.rb
Labels: maintenance

#2384 [close #2371] Do not log EOFError
  History.md
  lib/puma/client.rb
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: bug

#2389 Server - Consolidate option handling, small refactors, doc changes
  History.md
  lib/puma/runner.rb
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: maintenance

#2374 Refactor: extract worker process into separate class [changelog skip]
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/cluster/worker_handle.rb
  lib/puma/util.rb
Labels: feature, waiting-for-review
