Repository puma/puma, pull requests merged in 2020-04, with the labels that each got.

#2216 Set `Connection: closed` when running without request queueing
  History.md
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: bug, waiting-for-review

#2122 Pass queued requests to thread pool on server shutdown
  History.md
  lib/puma/client.rb
  lib/puma/reactor.rb
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: bug, waiting-for-review

#2124 JSON parse cluster worker stats instead of regex
  History.md
  lib/puma/cluster.rb
  lib/puma/server.rb
  lib/puma/single.rb
  test/test_cli.rb
  test/test_launcher.rb
Labels: maintenance, waiting-for-changes

#2220 ThreadPool concurrency refactoring
  History.md
  lib/puma/thread_pool.rb
  test/test_thread_pool.rb
Labels: bug, maintenance, waiting-for-review

#2218 Fix out_of_band hook
  History.md
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/test_puma_server.rb
Labels: bug, waiting-for-changes

#2226 The new way of allowing failures on GitHub Actions [changelog skip]
  .github/workflows/puma.yml
Labels: maintenance

#2221 Fix ThreadPool#shutdown timeout accuracy
  Gemfile
  History.md
  lib/puma/dsl.rb
  lib/puma/thread_pool.rb
  test/helper.rb
  test/test_puma_server.rb
  test/test_thread_pool.rb
Labels: feature, maintenance, waiting-for-changes

#2223 Support parallel tests in verbose progress reporting
  History.md
  test/helper.rb
  test/minitest/verbose.rb
  test/minitest/verbose_progress_plugin.rb
Labels: maintenance, waiting-for-review

#2143 add RAILS_MIN_THREADS, RAILS_MAX_THREADS, set default worker, preload…
  History.md
  lib/puma/configuration.rb
  lib/puma/detect.rb
  lib/puma/plugin.rb
  test/test_cli.rb
  test/test_config.rb
Labels: feature, waiting-for-changes

#2236 Prefer rackup file specified by CLI
  History.md
  lib/puma/dsl.rb
  test/config/with_rackup_from_dsl.rb
  test/test_integration_single.rb
Labels: bug, waiting-for-changes

#2240 [changelog skip] Move integration logging test to main test suite
  test/config/t1_conf.rb
  test/shell/run.rb
  test/shell/t1.rb
  test/test_integration_single.rb
  test/test_rack_handler.rb
Labels: maintenance, waiting-for-review

#2234 Improvements to out_of_band hook
  History.md
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/test_out_of_band_server.rb
  test/test_puma_server.rb
Labels: maintenance, waiting-for-review
