Repository puma/puma, pull requests merged in 2020-05, with the labels that each got.

#2248 [changelog skip] Add tests for ControlCLI when the supplied command is invalid or empty
  lib/puma/control_cli.rb
  test/test_pumactl.rb
Labels: maintenance

#2238 Add optional state file permissions
  History.md
  lib/puma/dsl.rb
  lib/puma/launcher.rb
  lib/puma/state_file.rb
  test/test_launcher.rb
Labels: feature, waiting-for-changes

#2253 Revert api change from #2086 introduce Puma.stats_hash api
  History.md
  lib/puma.rb
  puma.gemspec
  test/test_cli.rb
  test/test_integration_cluster.rb
  test/test_launcher.rb
Labels: maintenance

#2099 Experiment: Fork from existing worker process to optimize copy-on-write performance
  History.md
  docs/fork_worker.md
  docs/signals.md
  lib/puma/app/status.rb
  lib/puma/cli.rb
  lib/puma/cluster.rb
  lib/puma/control_cli.rb
  lib/puma/dsl.rb
  lib/puma/server.rb
  test/helpers/integration.rb
  test/test_integration_cluster.rb
Labels: perf, waiting-for-review

#2079 Inject small delay for busy workers to improve requests distribution
  History.md
  benchmarks/wrk/cpu_spin.sh
  lib/puma/dsl.rb
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/config/cpu_spin.rb
  test/helper.rb
  test/test_busy_worker.rb
Labels: feature, perf, waiting-for-review

#2256 Added `nakayoshi_fork` option.
  5.0-Upgrade.md
  History.md
  lib/puma/cli.rb
  lib/puma/cluster.rb
  lib/puma/dsl.rb
  lib/puma/thread_pool.rb
  test/test_integration_cluster.rb
  test/test_integration_single.rb
  test/test_puma_server.rb
Labels: feature

#2239 Refactor error handling in server accept loop
  History.md
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: bug, maintenance, waiting-for-changes

#2116 Fix rejecting HTTP requests when TLS1.3 is used by server
  History.md
  ext/puma_http11/mini_ssl.c
  lib/puma/minissl.rb
  test/test_puma_server_ssl.rb
Labels: bug, c-ext, ssl, waiting-for-changes

#2276 Fix errors on test_halt_unix [changelog skip]
  lib/puma/launcher.rb
  lib/puma/runner.rb
  test/test_integration_pumactl.rb
Labels: maintenance

#2267 Fix for spawning subprocesses with fork_worker option
  History.md
  lib/puma/cluster.rb
  test/test_integration_cluster.rb
Labels: bug

#2283 Minor: Add running_from to state_file
  lib/puma/launcher.rb
  lib/puma/state_file.rb
Labels: feature

#2287 Set CONTENT_LENGTH for chunked requests
  History.md
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: bug
