Repository puma/puma, pull requests merged in 2020-06, with the labels that each got.

#2288 Dynamically resolve rack.multithread/rack.multiprocess
  History.md
  lib/puma/binder.rb
  lib/puma/launcher.rb
  test/test_binder.rb
Labels: feature, waiting-for-changes

#2293 Unskip two jruby ssl tests that were hanging [changelog skip]
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  test/helpers/ssl.rb
  test/test_binder.rb
  test/test_cli.rb
  test/test_pumactl.rb
Labels: jruby, maintenance

#2292 Run CI using the default version of Bundler [changelog skip]
  .github/workflows/puma.yml
Labels: maintenance, waiting-for-review

#2250 Add unified detailed error logging
  lib/puma/error_logger.rb
  lib/puma/events.rb
  lib/puma/reactor.rb
  lib/puma/server.rb
  test/test_error_logger.rb
  test/test_events.rb
  test/test_puma_server_ssl.rb
Labels: feature, maintenance, waiting-for-review

#2275 Timeout unit tests on teardown [changelog skip]
  test/helper.rb
Labels: maintenance, waiting-for-review

#2295 resolve waiting counter problem
  History.md
  lib/puma/thread_pool.rb
  test/test_thread_pool.rb
Labels: bug, waiting-for-review
