Repository puma/puma, pull requests merged in 2020-11, with the labels that each got.

#2473 Remove use of json gem from WorkerHandle#ping!
  History.md
  lib/puma/cluster/worker.rb
  lib/puma/cluster/worker_handle.rb
  test/helpers/integration.rb
  test/test_worker_gem_independence.rb
  test/worker_gem_independence_test/new_json/Gemfile
  test/worker_gem_independence_test/new_json/config.ru
  test/worker_gem_independence_test/new_json/config/puma.rb
  test/worker_gem_independence_test/new_nio4r/Gemfile
  test/worker_gem_independence_test/new_nio4r/config.ru
  test/worker_gem_independence_test/new_nio4r/config/puma.rb
  test/worker_gem_independence_test/old_json/Gemfile
  test/worker_gem_independence_test/old_json/config.ru
  test/worker_gem_independence_test/old_json/config/puma.rb
  test/worker_gem_independence_test/old_nio4r/Gemfile
  test/worker_gem_independence_test/old_nio4r/config.ru
  test/worker_gem_independence_test/old_nio4r/config/puma.rb
Labels: bug, restart

#2472 Log the configuration if an env variable is provided
  History.md
  README.md
  lib/puma/configuration.rb
  lib/puma/launcher.rb
  test/test_config.rb
  test/test_launcher.rb
Labels: feature, waiting-for-review

#2475 Ignore forksafe threads for warning
  History.md
  lib/puma/cluster.rb
Labels: feature

#2479 Remove use of json gem
  Gemfile
  History.md
  lib/puma.rb
  lib/puma/app/status.rb
  lib/puma/json.rb
  test/config/prune_bundler_print_json_defined.rb
  test/test_cli.rb
  test/test_integration_cluster.rb
  test/test_json.rb
  test/test_worker_gem_independence.rb
  test/worker_gem_independence_test/new_json_with_puma_stats_after_fork/Gemfile
  test/worker_gem_independence_test/new_json_with_puma_stats_after_fork/config.ru
  test/worker_gem_independence_test/new_json_with_puma_stats_after_fork/config/puma.rb
  test/worker_gem_independence_test/old_json_with_puma_stats_after_fork/Gemfile
  test/worker_gem_independence_test/old_json_with_puma_stats_after_fork/config.ru
  test/worker_gem_independence_test/old_json_with_puma_stats_after_fork/config/puma.rb
Labels: bug, waiting-for-review

#2362 Add option to bind to systemd activated sockets
  History.md
  docs/systemd.md
  lib/puma/binder.rb
  lib/puma/cli.rb
  lib/puma/dsl.rb
  lib/puma/launcher.rb
  test/test_binder.rb
Labels: feature, waiting-for-review

#2477 Catch 'Error in reactor loop escaped: mode not supported for this object: r'
  History.md
  lib/puma/reactor.rb
Labels: bug, jruby, waiting-for-changes

#2487 control_cli.rb - all normal output should be to @stdout
  History.md
  lib/puma/control_cli.rb
Labels: bug, maintenance

#2485 Allow configuring query string max length
  History.md
  docs/compile_options.md
  ext/puma_http11/http11_parser.c
  ext/puma_http11/puma_http11.c
Labels: feature, waiting-for-changes

#2489 Fix JRuby ssl_cipher_list, add Puma::DSL.ssl_bind_str method
  History.md
  lib/puma/dsl.rb
  test/helpers/ssl.rb
  test/test_config.rb
Labels: bug, jruby

#2499 Bug: extconf.rb - fixup for 1.1.1 change from 1.1.0 [changelog skip]
  ext/puma_http11/extconf.rb
Labels: bug

#2498 Bug: Fix regex warnings in const.rb & test_launcher.rb [changelog skip]
  lib/puma/const.rb
  test/test_launcher.rb
Labels: bug
