Repository puma/puma, pull requests merged in 2020-12, with the labels that each got.

#2502 Fix typo in local #define name [changelog skip]
  ext/puma_http11/puma_http11.c
Labels: maintenance

#2501 [docs] compile_options.md: Mention option in heading [ci skip]
  docs/compile_options.md
Labels: docs

#2494 Fail build if compiling extensions raises warnings (#1953)
  .github/workflows/mri.yml
  .github/workflows/non_mri.yml
  History.md
  ext/puma_http11/extconf.rb
  ext/puma_http11/http11_parser.c
  ext/puma_http11/http11_parser.java.rl
  ext/puma_http11/http11_parser.rl
  ext/puma_http11/mini_ssl.c
  ext/puma_http11/org/jruby/puma/Http11Parser.java
Labels: maintenance, waiting-for-changes

#2486 Avoid mutating $stdout and $stderr
  History.md
  lib/puma/control_cli.rb
  lib/puma/error_logger.rb
  lib/puma/events.rb
  lib/puma/runner.rb
  test/test_error_logger.rb
  test/test_events.rb
Labels: feature, waiting-for-review

#2497 Bug: Fix Events#fire_on_stopped! double call [changelog skip]
  lib/puma/launcher.rb
  test/test_launcher.rb
Labels: bug, waiting-for-review

#2490 [SSL] Add ability to set verification flags
  History.md
  README.md
  ext/puma_http11/mini_ssl.c
  lib/puma/dsl.rb
  lib/puma/minissl.rb
  lib/puma/minissl/context_builder.rb
  test/test_binder.rb
  test/test_config.rb
Labels: feature, ssl, waiting-for-changes

#2510 Make illegal header matching more stringent
  History.md
  lib/puma/const.rb
  test/test_response_header.rb
Labels: bug

#2514 [ci skip] Improve quoting of bundle cflags
  docs/compile_options.md
Labels: c-ext, docs
