Repository puma/puma, pull requests merged in 2021-01, with the labels that each got.

#2520 Add #string method to Puma::NullIO
  History.md
  lib/puma/null_io.rb
  test/test_null_io.rb
Labels: maintenance

#2521 Build proper url instead of interpolating in `Puma::DSL#port`
  History.md
  lib/puma/dsl.rb
  test/test_rack_handler.rb
Labels: bug

#2522 Allow specifying the desired IO selector backend for nio4r
  History.md
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/reactor.rb
  lib/puma/server.rb
  test/config/with_symbol_convert.rb
  test/test_config.rb
  test/test_puma_server.rb
Labels: feature, waiting-for-changes

#2525 Docs for stats
  docs/stats.md
Labels: docs, waiting-for-changes

#2531 Remove Server#read_body
  History.md
  lib/puma/server.rb
Labels: maintenance

#2533 Binder - add/fix ssl 0.0.0.0/localhost logging, use ternary operator
  History.md
  lib/puma/binder.rb
  test/test_binder.rb
Labels: bug, waiting-for-review

#2529 Change 'Goodbye!' message to be output after listeners are closed
  History.md
  lib/puma/launcher.rb
Labels: feature, waiting-for-review

#2519 Fix SSL Context - minissl.c, minissl.rb, extconf.rb
  History.md
  ext/puma_http11/extconf.rb
  ext/puma_http11/mini_ssl.c
  lib/puma/minissl.rb
Labels: maintenance, perf, ssl, waiting-for-review

#2535 minissl.c - change dh1024 to dh2048 for SSL_CTX_set_tmp_dh
  History.md
  ext/puma_http11/mini_ssl.c
Labels: feature, ssl, waiting-for-changes
