Repository puma/puma, pull requests merged in 2021-04, with the labels that each got.

#2588 Define `UNPACK_TCP_STATE_FROM_TCP_INFO` in the right place
  lib/puma/server.rb
Labels: maintenance

#2590 [changelog skip] Reduce puma_parser struct padding
  ext/puma_http11/http11_parser.h
Labels: c-ext, perf

#2596 Server#closed_socket? - parameter may be a MiniSSL::Socket
  lib/puma/server.rb
Labels: bug, ssl

#2567 Handle segfault in Ruby 2.6.6 on thread-locals
  History.md
  lib/puma/cluster.rb
Labels: bug, waiting-for-review

#2607 Handle fatal error that has no backtrace
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: bug

#2564 Add support for Linux's abstract sockets
  lib/puma.rb
  lib/puma/binder.rb
  lib/puma/control_cli.rb
  test/test_pumactl.rb
  test/test_unix_socket.rb
Labels: feature, waiting-for-changes

#2605 Improve parsing of HTTP_HOST header
  lib/puma/request.rb
  test/test_puma_server.rb
Labels: bug, waiting-for-review

#2609 Reset peerip only if remote_addr_header is set
  lib/puma/client.rb
Labels: perf, refactor

#2613 Immediately unlink temporary files
  lib/puma/client.rb
Labels: bug

#2600 Refactor drain on shutdown
  lib/puma/queue_close.rb
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: refactor
