Repository puma/puma, pull requests merged in 2021-09, with the labels that each got.

#2688 Preserve BUNDLE_APP_CONFIG on worker fork
  lib/puma/launcher.rb
  test/bundle_app_config_test/.bundle/config
  test/bundle_app_config_test/Gemfile
  test/bundle_app_config_test/config.ru
  test/test_preserve_bundler_env.rb
Labels: bug

#2689 Add a semantic CLI option for no config file
  README.md
  lib/puma/cli.rb
Labels: feature

#2690 allow multiple after_worker_fork hooks
  lib/puma/dsl.rb
  test/test_config.rb
Labels: bug

#2654 add support for the PROXY protocol (v1 only)
  lib/puma/client.rb
  lib/puma/const.rb
  lib/puma/dsl.rb
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: feature, waiting-for-review

#2675 Fix performance of server-side SSL connection close.
  lib/puma/minissl.rb
Labels: waiting-for-changes, perf, ssl

#2700 More elaborate exception handling.
  lib/puma/server.rb
  test/helpers/integration.rb
  test/rackup/close_listeners.ru
  test/test_integration_single.rb
Labels: bug

#2702 Add support for APP_ENV environment variable
  README.md
  lib/puma/configuration.rb
  lib/puma/control_cli.rb
  test/test_cli.rb
  test/test_config.rb
  test/test_pumactl.rb
Labels: feature, waiting-for-changes
