Repository puma/puma, pull requests merged in 2021-11, with the labels that each got.

#2730 [jruby] a couple refactorings - avoid copy-ing bytes
  ext/puma_http11/org/jruby/puma/MiniSSL.java
Labels: jruby, waiting-for-review, refactor

#2741 CI - itermittent fix and RuboCop
  test/test_cli.rb
  test/test_thread_pool.rb
Labels: CI / Testing

#2731 Always send lowlevel_error response to client
  lib/puma/request.rb
  lib/puma/server.rb
  test/test_puma_server.rb
  test/test_response_header.rb
Labels: feature, waiting-for-review

#2744 test_http11: make `Digest` use thread-safe
  test/test_http11.rb
Labels: CI / Testing

#2746 [CI] Fix Timeout Errors when reading responses
  test/helpers/integration.rb
  test/test_integration_cluster.rb
Labels: CI / Testing

#2745 server.rb - rescue handling (`Errno::EBADF`) for `@notify.close`
  lib/puma/server.rb
Labels: bug

#2757 extconf.rb - fix openssl with old Windows builds
  ext/puma_http11/extconf.rb
Labels: windows, bug, ssl

#2760 Fix error message in test_verify_fail_if_client_unknown_ca
  test/test_puma_server_ssl.rb
Labels: ssl, CI / Testing
