Repository puma/puma, pull requests merged in 2021-03, with the labels that each got.

#2563 Don't close systemd activated socket on pumactl restart
  History.md
  lib/puma/binder.rb
Labels: feature

#2565 Print warning when running one-worker cluster
  History.md
  lib/puma/cluster.rb
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  test/test_config.rb
  test/test_integration_cluster.rb
Labels: feature

#2559 Add debug to worker timeout and startup. Closes #2528
  History.md
  lib/puma/cluster.rb
  lib/puma/cluster/worker_handle.rb
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_preserve_bundler_env.rb
  test/test_worker_gem_independence.rb
Labels: feature, waiting-for-review

#2573 Remove 'added an entry to History.md' requirement for PR's [ci skip]
  .github/pull_request_template.md
  .github/workflows/check_changelog.yml
Labels: maintenance

#2577 Minitest - Add code to group & summarize test skips [changelog skip]
  test/helper.rb
Labels: maintenance
