Repository puma/puma, pull requests merged in 2021-05, with the labels that each got.

#2591 systemd - fix event firing
  lib/puma/cluster.rb
  test/test_integration_systemd.rb
Labels: bug, systemd, waiting-for-review

#2628 Improvements to keepalive-connection shedding
  lib/puma/client.rb
  lib/puma/request.rb
  lib/puma/server.rb
Labels: bug, perf, waiting-for-review

#2629 Fix sigterm misbehavior
  lib/puma/cluster/worker.rb
Labels: bug, waiting-for-review

#2630 Gracefully handle Rack not accepting CLI options
  lib/puma/configuration.rb
Labels: bug, waiting-for-review

#2586 Add rack_url_scheme to Puma::DSL, allows setting of rack.url_scheme header
  lib/puma/binder.rb
  lib/puma/dsl.rb
  lib/puma/request.rb
  test/test_puma_server.rb
Labels: feature, waiting-for-review
