Repository puma/puma, pull requests merged in 2021-07, with the labels that each got.

#2656 Fix deadlock issue in thread pool
  lib/puma/thread_pool.rb
Labels: waiting-for-review

#2657 Better names for thread pool threads
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/test_thread_pool.rb
Labels: feature

#2666 Replace IO.select with IO#wait_* when checking a single IO
  lib/puma/client.rb
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/minissl.rb
  lib/puma/request.rb
  lib/puma/server.rb
  test/helpers/integration.rb
Labels: refactor
