Repository puma/puma, pull requests merged in 2021-02, with the labels that each got.

#2540 [ci skip] Add documentation on interlock issue in Rails development mode
  docs/rails_dev_mode.md
Labels: docs, waiting-for-changes

#2541 Move ssl detection to puma.rb [changelog skip]
  lib/puma.rb
  lib/puma/detect.rb
Labels: maintenance, waiting-for-review

#2543 Bug Fix - MiniSSL::Socket#write - use data.byteslice(wrote..-1)
  History.md
  lib/puma/minissl.rb
Labels: bug, ssl, waiting-for-review

#2549 Set @env[CONTENT_LENGTH] value as string.
  History.md
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: bug

#2550 server.rb - properly cork & uncork ssl clients
  History.md
  lib/puma/request.rb
  lib/puma/server.rb
Labels: bug, ssl, waiting-for-changes, waiting-for-review

#2553 Add `#flush` and `#sync` methods to `Puma::NullIO`
  History.md
  lib/puma/null_io.rb
  test/test_events.rb
  test/test_null_io.rb
Labels: bug, waiting-for-review

#2557 Restore sync=true on global stdout/stderr streams
  History.md
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/runner.rb
  test/rackup/write_to_stdout.ru
  test/test_integration_single.rb
Labels: bug, waiting-for-review
