Repository puma/puma, pull requests merged in 2021-12, with the labels that each got.

#2751 [CI] Fix intermittent integration test failures/errors
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_preserve_bundler_env.rb
Labels: maintenance

#2759 Add worker_check_interval configuration option
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/configuration.rb
  lib/puma/const.rb
  lib/puma/dsl.rb
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_launcher.rb
Labels: feature, waiting-for-review

#2733 Keep thread names under 15 characters
  lib/puma/cluster/worker.rb
  lib/puma/plugin.rb
  lib/puma/runner.rb
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/test_integration_cluster.rb
  test/test_thread_pool.rb
Labels: feature, waiting-for-changes

#2742 server.rb - refactor code using @options[:remote_address]
  lib/puma/server.rb
Labels: waiting-for-review, refactor

#2725 Add ability to specify custom logger
  lib/puma/dsl.rb
  test/config/custom_logger.rb
  test/test_config.rb
Labels: feature, contrib-wanted, waiting-for-review

#2768 [CI] Remove the t3-pid file after tests
  test/test_pumactl.rb
Labels: CI / Testing
