Repository puma/puma, pull requests merged in 2022-05, with the labels that each got.

#2869 Github Actions. Run test only if linter finished successfully.
  .github/workflows/mri.yml
  .github/workflows/non_mri.yml
  .github/workflows/tests.yaml
  README.md
Labels: CI / Testing

#2879 [CI] Add OpenSSL 3 testing - Ubuntu-22.04 - 3.1 & head
  .github/workflows/tests.yaml
Labels: ssl, CI / Testing

#2875 Minor: Export puma/ruby versions in /stats
  lib/puma/cluster.rb
  lib/puma/runner.rb
  lib/puma/single.rb
  test/test_cli.rb
Labels: feature

#2882 Fix "log_writer.rb:59:in `write': deadlock; recursive locking (ThreadError)"
  lib/puma/log_writer.rb
  test/helpers/integration.rb
  test/test_integration_pumactl.rb
Labels: bug

#2884 [jruby] improve the truststore option
  examples/puma/client-certs/unknown_ca_store.p12
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  lib/puma/dsl.rb
  lib/puma/minissl.rb
  lib/puma/minissl/context_builder.rb
  test/test_config.rb
  test/test_puma_server_ssl.rb
Labels: feature, jruby, maintenance, waiting-for-review

#2885 extconf.rb - don't use pkg_config('openssl') if '--with-openssl-dir' is used
  ext/puma_http11/extconf.rb
Labels: bug, ssl, c-ext

#2887 [CI] rescue more errors in teardown & wait_for_server_to_boot methods, RubyGems
  .github/workflows/tests.yaml
  test/helpers/integration.rb
  test/test_out_of_band_server.rb
Labels: CI / Testing

#2886 [jruby] enable TLSv1.3 support
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  lib/puma/minissl.rb
  test/test_puma_server_ssl.rb
Labels: feature, ssl, jruby
