Repository puma/puma, pull requests merged in 2022-11, with the labels that each got.

#3008 Skip duplicate Github Actions runs (#2929)
  .github/workflows/rack2.yaml
  .github/workflows/ragel.yml
  .github/workflows/skip_duplicate_workflow_runs.yaml
  .github/workflows/tests.yaml
Labels: CI / Testing

#3009 [ci skip] Include `ca` option for SSL bind and mTLS example
  lib/puma/dsl.rb
Labels: docs

#3002 Correctly close app body for all code paths
  lib/puma/request.rb
  test/test_puma_server.rb
  test/test_rack_server.rb
Labels: bug

#3005 Handle waking up a closed selector in Reactor#add
  lib/puma/reactor.rb
Labels: waiting-for-changes, CI / Testing

#3015 Add note about HTTP method change in 6.0
  6.0-Upgrade.md
  History.md
Labels: docs

#3018 [CI] two small CI fixes
  test/helpers/integration.rb
  test/test_rack_server.rb
Labels: CI / Testing

#3004 Fixup response processing, enumerable bodies
  .github/workflows/turbo-rails.yml
  lib/puma/const.rb
  lib/puma/io_buffer.rb
  lib/puma/request.rb
  test/test_cli.rb
  test/test_puma_server.rb
Labels: bug
