Repository puma/puma, pull requests merged in 2022-04, with the labels that each got.

#2847 Fail hard if SSL certs or keys cannot be read by user
  lib/puma/minissl.rb
  test/test_minissl.rb
Labels: bug, ssl

#2848 Fail hard if SSL certs or keys are invalid
  ext/puma_http11/mini_ssl.c
  test/test_puma_server_ssl.rb
Labels: bug, ssl

#2852 5-6-stable branch - fix tests
  test/test_binder.rb
  test/test_request_invalid.rb
Labels: CI / Testing

#2849 [jruby] support a truststore option
  Rakefile
  examples/puma/client-certs/ca_store.p12
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  lib/puma/minissl.rb
  test/test_puma_server_ssl.rb
Labels: feature, waiting-for-review, breaking change

#2855 Escape SSL cert and filenames
  lib/puma/dsl.rb
  lib/puma/util.rb
  test/test_config.rb
Labels: bug, ssl

#2840 Allow configuring request uri max length & request path max length
  docs/compile_options.md
  ext/puma_http11/puma_http11.c
Labels: feature, waiting-for-review

#2861 Fix rack.after_reply exceptions breaking connections
  lib/puma/request.rb
  test/test_rack_server.rb
Labels: bug

#2864 MiniSSL - detect SSL_CTX_set_dh_auto
  ext/puma_http11/extconf.rb
  ext/puma_http11/mini_ssl.c
Labels: bug, ssl, c-ext
