Repository puma/puma, pull requests merged in 2022-02, with the labels that each got.

#2797 Refactor: Extract prune_bundler code into its own class (no logic change)
  lib/puma/launcher.rb
  lib/puma/launcher/bundle_pruner.rb
  test/test_bundle_pruner.rb
  test/test_launcher.rb
Labels: waiting-for-changes, refactor

#2798 [WIP] Refactor: Split out LogWriter from Events (no logic change)
  examples/puma/client-certs/run_server_with_certs.rb
  lib/puma/binder.rb
  lib/puma/cli.rb
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/configuration.rb
  lib/puma/control_cli.rb
  lib/puma/events.rb
  lib/puma/launcher.rb
  lib/puma/launcher/bundle_pruner.rb
  lib/puma/log_writer.rb
  lib/puma/minissl/context_builder.rb
  lib/puma/request.rb
  lib/puma/runner.rb
  lib/puma/server.rb
  lib/puma/systemd.rb
  lib/puma/util.rb
  lib/rack/handler/puma.rb
  test/helper.rb
  test/test_binder.rb
  test/test_bundle_pruner.rb
  test/test_busy_worker.rb
  test/test_cli.rb
  test/test_config.rb
  test/test_events.rb
  test/test_launcher.rb
  test/test_log_writer.rb
  test/test_out_of_band_server.rb
  test/test_puma_localhost_authority.rb
  test/test_puma_server.rb
  test/test_puma_server_ssl.rb
  test/test_response_header.rb
  test/test_web_server.rb
Labels: waiting-for-changes, refactor

#2830 test_binder.rb - split out test causing issues when run parallel
  test/test_binder.rb
Labels: CI / Testing

#2817 Do not remove pre-existing socket after USR2+TERM (#2816)
  lib/puma/binder.rb
  test/test_integration_cluster.rb
Labels: waiting-for-changes, bug, contrib-wanted
