Repository puma/puma, pull requests merged in 2022-06, with the labels that each got.

#2888 log_writer.rb - refactor, add internal_write method
  lib/puma/log_writer.rb
Labels: refactor

#2890 [fix] TLS verification hang on JRuby
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  test/test_integration_ssl.rb
Labels: bug, ssl, jruby

#2868 Puma::ControlCLI - allow refork command to be sent as a request
  lib/puma/app/status.rb
  lib/puma/control_cli.rb
  lib/puma/launcher.rb
  test/test_integration_cluster.rb
  test/test_integration_pumactl.rb
  test/test_pumactl.rb
Labels: feature, bug, waiting-for-review

#2883 NullIO#closed? should return false
  lib/puma/null_io.rb
  test/test_null_io.rb
Labels: bug
