Repository puma/puma, pull requests merged in 2022-10, with the labels that each got.

#2984 [CI] test files - use unlink in ensure when appropriate
  test/test_integration_cluster.rb
  test/test_integration_single.rb
  test/test_launcher.rb
  test/test_pumactl.rb
Labels: CI / Testing

#2988 Use :nodoc: to limit public API [ci skip]
  lib/puma/client.rb
  lib/puma/cluster/worker.rb
  lib/puma/cluster/worker_handle.rb
  lib/puma/request.rb
Labels: refactor

#2994 [CI] - remove macOS 10.15 jobs, unsupported as of 01-Dec-2022
  .github/workflows/tests.yaml
Labels: CI / Testing

#2981 Fix path could be nil in test_puma_server tests
  test/helper.rb
  test/test_puma_server.rb
Labels: waiting-for-changes, CI / Testing

#3001 [CI] Fix TruffleRuby - TestPumaServer#test_lowlevel_error_message_without_backtrace
  test/test_puma_server.rb
Labels: CI / Testing
