Repository puma/puma, pull requests merged in 2022-12, with the labels that each got.

#3031 Skip Windows UNIXSocket tests for now
  lib/puma.rb
  test/helper.rb
Labels: CI / Testing

#3032 6.0.1
  .github/workflows/turbo-rails.yml
  History.md
  lib/puma/const.rb
Labels: maintenance

#3016 Refactor const.rb - freeze
  lib/puma/const.rb
Labels: refactor

#3035 Remove use of etc and time gems in Puma
  lib/puma.rb
  lib/puma/cluster.rb
  lib/puma/runner.rb
  lib/puma/single.rb
  test/test_integration_cluster.rb
Labels: refactor

#3048 CI: remove ubuntu-18.04 jobs
  .github/workflows/tests.yaml
Labels: maintenance, CI / Testing

#3049 CI: add Ruby 3.2.0 jobs
  .github/workflows/rack2.yaml
  .github/workflows/tests.yaml
  .github/workflows/turbo-rails.yml
Labels: maintenance, CI / Testing
