Repository puma/puma, pull requests merged in 2022-09, with the labels that each got.

#2924 Prefix all environment variables with `PUMA_`
  .github/workflows/tests.yaml
  Rakefile
  ext/puma_http11/extconf.rb
  test/config/cpu_spin.rb
Labels: feature, breaking change

#2933 Remove nakayoshi GC
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/dsl.rb
  lib/puma/util.rb
  test/test_integration_cluster.rb
Labels: feature, breaking change

#2923 IO/copy stream
  benchmarks/wrk/big_file.sh
  lib/puma/request.rb
  test/rackup/big_file.ru
  test/test_puma_server.rb
Labels: windows, waiting-for-changes

#2871 Fixup SERVER_PROTOCOL & HTTP_VERSION headers
  ext/puma_http11/http11_parser.c
  ext/puma_http11/http11_parser.h
  ext/puma_http11/http11_parser.java.rl
  ext/puma_http11/http11_parser.rl
  ext/puma_http11/http11_parser_common.rl
  ext/puma_http11/org/jruby/puma/Http11.java
  ext/puma_http11/org/jruby/puma/Http11Parser.java
  ext/puma_http11/puma_http11.c
  lib/puma/binder.rb
  lib/puma/request.rb
  test/rackup/env-dump.ru
  test/test_http10.rb
  test/test_http11.rb
Labels: bug, breaking change

#2940 Make wait_for_less_busy_worker default
  lib/puma/configuration.rb
Labels: feature, perf, breaking change

#2928 Refactor/move configuration defaults
  lib/puma/cli.rb
  lib/puma/configuration.rb
  lib/puma/const.rb
  lib/puma/dsl.rb
  lib/puma/server.rb
  lib/rack/handler/puma.rb
  test/test_cli.rb
  test/test_config.rb
  test/test_integration_cluster.rb
  test/test_launcher.rb
Labels: waiting-for-review, refactor, breaking change

#2941 Remove thread name respond to check for Puma 6
  lib/puma.rb
Labels: maintenance

#2943 Remove QueueClose patch for Puma 6
  lib/puma/queue_close.rb
Labels: maintenance

#2944 Remove the extra require for OpenSSL for Ruby 2.3 on Windows
  lib/puma/binder.rb
Labels: maintenance

#2946 Remove Ruby 2.2 workaround
  lib/puma/server.rb
Labels: maintenance

#2947 Remove more unneccessary Ruby version code
  Gemfile
  ext/puma_http11/extconf.rb
  test/helper.rb
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_puma_server_ssl.rb
Labels: maintenance

#2948 Removes debug info from tests by default
  .github/workflows/rack2.yaml
  .github/workflows/ragel.yml
  .github/workflows/tests.yaml
  CONTRIBUTING.md
  Rakefile
  test/helper.rb
  test/test_puma_server_ssl.rb
Labels: waiting-for-changes, CI / Testing

#2932 Do not raise error on CONNECT
  lib/puma/const.rb
  lib/puma/request.rb
  test/test_web_server.rb
Labels: feature

#2896 Response refactor, increase requests-per-second, body type handling
  lib/puma/client.rb
  lib/puma/io_buffer.rb
  lib/puma/request.rb
  test/test_persistent.rb
  test/test_puma_server.rb
  test/test_rack_server.rb
  test/test_response_header.rb
Labels: perf, waiting-for-review, refactor, breaking change

#2846 OpenSSL - allow session reuse via a 'reuse' ssl_bind method or bind string query parameter
  ext/puma_http11/extconf.rb
  ext/puma_http11/mini_ssl.c
  lib/puma/dsl.rb
  lib/puma/minissl.rb
  lib/puma/minissl/context_builder.rb
  test/test_integration_ssl_session.rb
Labels: feature, ssl, c-ext

#2953 Support request_body_wait metric with higher precision
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: feature, breaking change

#2942 Move threadpool init out of server
  lib/puma/configuration.rb
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/test_busy_worker.rb
  test/test_out_of_band_server.rb
  test/test_puma_server.rb
  test/test_thread_pool.rb
Labels: refactor

#2907 Allow to use `preload_app!` with `fork_worker`
  docs/fork_worker.md
  lib/puma/cluster.rb
Labels: feature

#2956 minissl.c - immediate ruby_memcheck fixes
  ext/puma_http11/mini_ssl.c
Labels: bug, ssl, c-ext

#2960 Make Request normalize_env private for Puma 6
  lib/puma/request.rb
Labels: refactor, breaking change

#2958 Remove unused KEYS_NOT_TO_PERSIST_IN_STATE for Puma 6
  lib/puma/cli.rb
  lib/puma/launcher.rb
Labels: refactor, breaking change

#2963 Allow fail on truffle for now
  .github/workflows/tests.yaml
Labels: CI / Testing

#2961 GitHub Codespaces
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: important!, maintenance, waiting-for-review

#2917 Allow `run_hooks` to pass a hash to blocks for use later
  lib/puma/cluster/worker.rb
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  test/config/hook_data.rb
  test/helpers/integration.rb
  test/test_integration_cluster.rb
Labels: feature, waiting-for-changes, waiting-for-review

#2965 Revert change to Server#initialize (new) method signature from #2798
  lib/puma/launcher.rb
  lib/puma/runner.rb
  lib/puma/server.rb
  test/test_busy_worker.rb
  test/test_integration_ssl.rb
  test/test_log_writer.rb
  test/test_out_of_band_server.rb
  test/test_persistent.rb
  test/test_puma_localhost_authority.rb
  test/test_puma_server.rb
  test/test_puma_server_ssl.rb
  test/test_request_invalid.rb
  test/test_response_header.rb
  test/test_web_server.rb
Labels: refactor

#2970 GitHub Workflows security hardening
  .github/workflows/rack2.yaml
  .github/workflows/ragel.yml
  .github/workflows/tests.yaml
Labels: CI / Testing

#2972 [CI] - Allow failure on macOS TruffleRuby for now
  .github/workflows/tests.yaml
Labels: CI / Testing

#2966 puma.rb - autoload LogWriter for non-standard loading
  lib/puma.rb
  lib/puma/cli.rb
Labels: refactor

#2968 Runner & subclasses - instance variable cleanup
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/runner.rb
  lib/puma/single.rb
Labels: refactor

#2969 Updates for LogWriter
  lib/puma/binder.rb
  lib/puma/cluster.rb
  lib/puma/runner.rb
Labels: refactor

#2967 Stop 'deadlock; recursive locking (ThreadError)' in LogWriter
  lib/puma/error_logger.rb
  lib/puma/log_writer.rb
Labels: bug

#2971 [CI] - fixup various test suite issues
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_integration_single.rb
  test/test_plugin.rb
  test/test_puma_server.rb
  test/test_rack_server.rb
Labels: CI / Testing

#2973 [CI] test_puma_server.rb - running parallel, fixup tests that stub
  test/test_puma_server.rb
Labels: CI / Testing

#2976 103 RuboCop fixes
  .rubocop.yml
  benchmarks/local/bench_base.rb
  benchmarks/local/response_time_wrk.rb
  bin/puma-wild
  lib/puma/binder.rb
  lib/puma/client.rb
  lib/puma/cluster.rb
  lib/puma/dsl.rb
  lib/puma/jruby_restart.rb
  lib/puma/launcher/bundle_pruner.rb
  lib/puma/minissl.rb
  lib/puma/rack/builder.rb
  lib/puma/reactor.rb
  lib/puma/request.rb
  lib/puma/runner.rb
  lib/puma/server.rb
  lib/puma/single.rb
  lib/puma/state_file.rb
  lib/puma/thread_pool.rb
  test/helper.rb
  test/helpers/integration.rb
  test/minitest/verbose_progress_plugin.rb
  test/rackup/ci_array.ru
  test/rackup/ci_chunked.ru
  test/rackup/ci_select.ru
  test/rackup/ci_string.ru
  test/rackup/env-dump.ru
  test/test_busy_worker.rb
  test/test_cli.rb
  test/test_config.rb
  test/test_integration_cluster.rb
  test/test_integration_ssl_session.rb
  test/test_integration_systemd.rb
  test/test_out_of_band_server.rb
  test/test_persistent.rb
  test/test_puma_localhost_authority.rb
  test/test_puma_server_ssl.rb
  test/test_pumactl.rb
  test/test_rack_handler.rb
  test/test_rack_server.rb
  test/test_request_invalid.rb
  test/test_worker_gem_independence.rb
Labels: waiting-for-review, refactor

#2978 [CI] PR #2976 - Fix RuboCop mistake - test/test_integration_cluster.rb
  test/test_integration_cluster.rb
Labels: CI / Testing

#2979 [CI] misc updates to test files
  test/helper.rb
  test/helpers/integration.rb
  test/test_puma_server_ssl.rb
Labels: CI / Testing
