Repository puma/puma, pull requests merged in 2022-01, with the labels that each got.

#2773 Alternate worker culling strategy
  lib/puma/cluster.rb
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  test/test_integration_cluster.rb
Labels: feature

#2784 Remove yaml (psych) requirement in StateFile
  lib/puma/cli.rb
  lib/puma/launcher.rb
  lib/puma/state_file.rb
  test/test_cli.rb
Labels: feature, refactor

#2780 Allow backlog parameter to be set with ssl_bind DSL
  docs/architecture.md
  lib/puma/binder.rb
  lib/puma/dsl.rb
  test/test_binder.rb
  test/test_config.rb
  test/test_thread_pool.rb
Labels: feature

#2785 Fix warning from Ruby master (will be 3.2.0)
  ext/puma_http11/mini_ssl.c
  test/test_puma_server_ssl.rb
Labels: bug, ssl, c-ext

#2794 In fork_worker mode, worker_culling_strategy "oldest" shouldn't cull worker 0
  lib/puma/cluster.rb
  test/test_integration_cluster.rb
Labels: feature, waiting-for-review

#2764 Support `localhost` integration in `ssl_bind`
  lib/puma/binder.rb
  lib/puma/dsl.rb
  test/config/ssl_self_signed_config.rb
  test/test_config.rb
  test/test_integration_ssl.rb
Labels: feature, waiting-for-review

#2799 Log environment using option value
  lib/puma/runner.rb
Labels: bug

#2800 Updates for OpenSSL 3
  ext/puma_http11/extconf.rb
  ext/puma_http11/mini_ssl.c
Labels: contrib-wanted, ssl, waiting-for-review

#2807 Fix two 'old-style-definition' compile warning
  ext/puma_http11/mini_ssl.c
  ext/puma_http11/puma_http11.c
Labels: bug, c-ext

#2810 Fix `Puma::StateFile#load` incompatibility
  lib/puma/state_file.rb
  test/test_state_file.rb
Labels: bug

#2740 Add support for streaming bodies.
  lib/puma/request.rb
  test/test_puma_server.rb
Labels: feature, waiting-for-changes

#2795 Refactor Launcher#run to increase readability (no logic change)
  lib/puma/launcher.rb
Labels: waiting-for-review, refactor

#2774 Add a couple of accessors
  lib/puma/cluster.rb
  lib/puma/runner.rb
Labels: feature, waiting-for-changes
