Repository puma/puma, pull requests merged in 2022-08, with the labels that each got.

#2909 5.6.5 release note
  History.md
Labels: maintenance

#2903 Ruby 3.2 will have native IO#wait_* methods, don't require io/wait
  lib/puma/detect.rb
  lib/puma/log_writer.rb
  lib/puma/minissl.rb
  lib/puma/server.rb
Labels: refactor

#2904 [jruby] allow truststore without password
  examples/puma/client-certs/ca_store.jks
  ext/puma_http11/org/jruby/puma/MiniSSL.java
  test/test_puma_server_ssl.rb
Labels: feature, ssl, jruby

#2897 Load the configuration before passing it to the binder:
  lib/puma/launcher.rb
  test/config/rack_url_scheme.rb
  test/rackup/url_scheme.ru
  test/test_integration_single.rb
  test/test_puma_server.rb
Labels: bug
