Repository puma/puma, pull requests merged in 2023-09, with the labels that each got.

#3209 Feature | Shutdown on idle
  lib/puma/cli.rb
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/server.rb
  test/test_integration_single.rb
  test/test_puma_server.rb
Labels: feature, waiting-for-changes

#3179 context_builder.rb - require openssl if verify_mode != 'none'
  ext/puma_http11/mini_ssl.c
  lib/puma/minissl.rb
  lib/puma/minissl/context_builder.rb
  test/helpers/integration.rb
  test/helpers/test_puma.rb
  test/helpers/test_puma/puma_socket.rb
  test/test_integration_ssl.rb
Labels: bug, ssl, CI / Testing

#3233 integration.rb - less blocking in wait_for_server_to_* methods
  .github/workflows/tests.yaml
  test/config/event_on_booted_exit.rb
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_integration_single.rb
  test/test_plugin_systemd_jruby.rb
  test/test_puma_server.rb
Labels: maintenance

#3225 [Fix #2786] Worker 0 timing out during phased restart
  lib/puma/cluster.rb
  test/helper.rb
  test/test_integration_cluster.rb
Labels: waiting-for-changes, bug

#3238 Fixup macOS detection
  lib/puma/detect.rb
  test/helpers/integration.rb
  test/helpers/tmp_path.rb
Labels: maintenance

#3237 [CI] - move test_control_gc_stats_* from test_cli.rb to test_integration_pumactl.rb, misc
  test/helpers/integration.rb
  test/test_cli.rb
  test/test_integration_pumactl.rb
Labels: maintenance, CI / Testing

#3240 [CI] test_rack_handler.rb - fix test ensure when skipped
  test/test_rack_handler.rb
Labels: maintenance, CI / Testing

#3239 [CI] test_pumactl.rb - use port 0 on server, misc
  test/config/app.rb
  test/helpers/test_puma/puma_socket.rb
  test/test_pumactl.rb
Labels: maintenance, CI / Testing
