Repository puma/puma, pull requests merged in 2023-02, with the labels that each got.

#3066 Update turbo-rails.yml
  .github/workflows/turbo-rails.yml
Labels: CI / Testing

#3006 Periodically send status to systemd
  lib/puma/launcher.rb
  lib/puma/plugin/systemd.rb
  lib/puma/systemd.rb
  test/test_plugin_systemd.rb
Labels: feature, systemd, waiting-for-review

#3076 [CI] turbo-rails is now passing
  .github/workflows/turbo-rails.yml
Labels: CI / Testing

#3065 Allow setting TCP low_latency with SSL listener, minor fixes
  lib/puma/binder.rb
  lib/puma/dsl.rb
  lib/puma/request.rb
  test/rackup/hello-bind_rack3.ru
  test/test_binder.rb
  test/test_config.rb
Labels: bug

#3077 Refactor test_plugin_systemd.rb, fix for TruffleRuby
  test/test_plugin_systemd.rb
Labels: CI / Testing

#3061 Fixup code for use with rackup gem (may be used with rack 3)
  Gemfile
  lib/puma/rack_default.rb
  lib/rack/handler/puma.rb
  test/test_rack_handler.rb
Labels: waiting-for-changes, bug

#3078 6.1.0 The Way Up
  History.md
  lib/puma/const.rb
Labels: maintenance

#3083 [CI] Integration tests - add parameter to allow TestIntegration#cli_server to change ENV
  test/helpers/integration.rb
  test/test_plugin_systemd.rb
Labels: CI / Testing

#3080 Allow ::Rack::Handler::Puma.run to work regardless of whether Rack/Rackup are loaded
  lib/rack/handler/puma.rb
  test/test_rack_handler.rb
  test/test_rack_server.rb
Labels: bug

#3084 [CI] Fix error message change in Ruby master
  test/test_puma_server.rb
Labels: maintenance, CI / Testing

#2709 Add on_booted event
  README.md
  lib/puma/cli.rb
  lib/puma/dsl.rb
  lib/rack/handler/puma.rb
  test/config/event_on_booted.rb
  test/config/event_on_booted_exit.rb
  test/test_integration_cluster.rb
  test/test_integration_single.rb
  test/test_rack_handler.rb
Labels: feature, waiting-for-review

#3079 Don't use the systemd plugin on JRuby
  lib/puma/detect.rb
  lib/puma/launcher.rb
  test/helper.rb
  test/test_plugin_systemd.rb
  test/test_plugin_systemd_jruby.rb
Labels: bug, systemd, jruby
