Repository puma/puma, pull requests merged in 2023-05, with the labels that each got.

#3129 Misc lib file fixes - trapping additional errors, CI helper
  lib/puma/binder.rb
  lib/puma/reactor.rb
  lib/puma/server.rb
  lib/puma/thread_pool.rb
Labels: bug, CI / Testing

#3147 [CI] test_integration_ssl_session.rb - use SSLSockets instead of curl
  test/test_integration_ssl_session.rb
  test/test_plugin_systemd_jruby.rb
Labels: CI / Testing

#3151 Clarify Reactor#initialize
  lib/puma/reactor.rb
Labels: refactor

#3152 [CI] turbo-rails - Capybara is fixed
  .github/workflows/turbo-rails.yml
Labels: CI / Testing

#3153 Store Tempfiles in ./tmp
  test/helpers/tmp_path.rb
Labels: CI / Testing

#3149 [CI] Remove rack2.yaml workflow, add jobs to tests.yaml
  .github/workflows/rack2.yaml
  .github/workflows/tests.yaml
Labels: CI / Testing

#3159 [CI] Use <<~ for heredocs
  test/test_integration_cluster.rb
  test/test_integration_ssl.rb
  test/test_puma_server.rb
Labels: CI / Testing

#3157 [CI] test_redirect_io.rb - fixup for intermittent failures
  test/test_redirect_io.rb
Labels: CI / Testing

#3160 [CI] - Use RubyGems 3.3.26 for Ruby 2.4 thru 2.6 (was 3.3.14)
  .github/workflows/tests.yaml
Labels: CI / Testing

#3162 const.rb - Update Puma::HTTP_STATUS_CODES
  lib/puma/const.rb
  test/test_puma_server.rb
Labels: refactor

#3163 Don't send 103 early hints response when only invalid headers are used
  lib/puma/request.rb
  test/test_response_header.rb
Labels: bug

#3161 Puma error responses - remove fingerprints to indicate Puma
  lib/puma/const.rb
Labels: feature

#3106 Add dsl method `supported_http_methods`
  6.0-Upgrade.md
  lib/puma/const.rb
  lib/puma/dsl.rb
  lib/puma/request.rb
  lib/puma/server.rb
  test/test_puma_server.rb
  test/test_web_server.rb
Labels: feature, waiting-for-review
