Repository puma/puma, pull requests merged in 2023-10, with the labels that each got.

#3242 [CI] test_cli.rb - use PumaSocket, remove native sockets, net/http
  test/helpers/test_puma/puma_socket.rb
  test/test_cli.rb
Labels: maintenance, CI / Testing

#3243 [CI] test_puma_server_ssl.rb - add PumaSocket, remove net/http
  test/test_puma_server_ssl.rb
Labels: maintenance, CI / Testing

#3244 [CI] test_puma_localhost_authority.rb - use PumaSocket, remove net/http
  test/test_puma_localhost_authority.rb
Labels: maintenance, CI / Testing

#3235 [Fix #3228] `idle-timeout` not working in cluster mode
  lib/puma/cluster/worker.rb
  lib/puma/runner.rb
  lib/puma/server.rb
  test/test_integration_cluster.rb
  test/test_integration_single.rb
Labels: bug

#3249 [CI] test.yaml 'NON-MRI: ubuntu-22.04 jruby no SSL' test timeout
  .github/workflows/tests.yaml
Labels: maintenance, CI / Testing

#3252 [CI] test_puma_server_ssl.rb - add Errno::ECONNABORTED to invalid cert errors
  test/test_puma_server_ssl.rb
Labels: maintenance, CI / Testing

#3256 DSL#warn_if_in_single_mode - fixup when workers set via CLI
  lib/puma/dsl.rb
  test/test_integration_cluster.rb
Labels: bug

#3259 [CI] Fix macOS TruffleRuby
  .github/workflows/tests.yaml
  ext/puma_http11/extconf.rb
Labels: ssl, c-ext, CI / Testing

#3265 dsl.rb - fix warn_if_in_single_mode when WEB_CONCURRENCY is set
  lib/puma/dsl.rb
  test/test_integration_cluster.rb
Labels: bug

#3268 Use test_runner for tests
  .github/workflows/tests.yaml
  test/runner
  test/runner.cmd
Labels: CI / Testing

#3270 MiniSSL.java - set serialVersionUID, fix RaiseException deprecation
  ext/puma_http11/org/jruby/puma/MiniSSL.java
Labels: bug, ssl, jruby

#3271 extconf.rb - fixup to detect openssl info in Ruby build
  ext/puma_http11/extconf.rb
Labels: bug, ssl, c-ext
