Repository puma/puma, pull requests merged in 2023-08, with the labels that each got.

#3195 Add on_thread_start_hook
  lib/puma/dsl.rb
  lib/puma/thread_pool.rb
  test/test_config.rb
  test/test_thread_pool.rb
Labels: feature

#3204 Added a Meaningful error msg for control server port taken
  lib/puma/runner.rb
Labels: feature, waiting-for-changes

#3191 Remove `Forwardable` dependency (possible conversion to bundled gem)
  lib/puma/client.rb
  lib/puma/server.rb
Labels: refactor
