Repository puma/puma, pull requests merged in 2023-01, with the labels that each got.

#3051 [CI] Cleanup turbo_rails.yml
  .github/workflows/turbo-rails.yml
Labels: CI / Testing

#3040 Introduce the ability to return 413: payload too large for requests
  lib/puma/client.rb
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/request.rb
  lib/puma/server.rb
  test/test_config.rb
  test/test_puma_server.rb
Labels: feature, waiting-for-review

#3011 Add built-in systemd notify support
  Gemfile
  docs/systemd.md
  lib/puma/launcher.rb
  lib/puma/sd_notify.rb
  lib/puma/systemd.rb
  test/test_integration_systemd.rb
Labels: feature, systemd

#3036 Log loaded extensions when `PUMA_DEBUG` is set
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/log_writer.rb
  lib/puma/runner.rb
  lib/puma/single.rb
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_integration_pumactl.rb
  test/test_integration_single.rb
Labels: feature

#3060 [CI] - update RubyGems for Ruby 2.6, eliminate warnings
  .github/workflows/tests.yaml
Labels: CI / Testing

#3064 [CI] test_rack_server.rb - remove use of Open3, set HOST constant
  test/test_rack_server.rb
Labels: CI / Testing

#3056 Add workflow for ensuring PRs are labeled
  .github/workflows/ensure_pull_requests_are_labeled.yml
Labels: waiting-for-changes, maintenance

#3062 Reduce memory usage for large file uploads
  benchmarks/local/sinatra/Gemfile
  benchmarks/local/sinatra/README.md
  benchmarks/local/sinatra/config.ru
  benchmarks/local/sinatra/puma.rb
  lib/puma/client.rb
Labels: waiting-for-changes, perf

#3058 WebSocket support?
  .github/workflows/rack_conform.yml
  lib/puma/request.rb
  test/test_puma_server.rb
  test/test_puma_server_partial_hijack.rb
Labels: feature, waiting-for-review
