Repository puma/puma, pull requests merged in 2023-04, with the labels that each got.

#3118 Fix NameError by adding ::operator
  lib/rack/handler/puma.rb
Labels: bug

#3116 [CI] Delete ensure_pull_requests_are_labeled.yml workflow
  .github/workflows/ensure_pull_requests_are_labeled.yml
Labels: CI / Testing

#3119 [CI] Modify test for PR #3118
  test/test_rack_handler.rb
Labels: CI / Testing

#3138 [CI] helper.rb - collapse 'Skips' section in Actions test logs
  test/helper.rb
Labels: CI / Testing

#3133 Support decryption of SSL key
  README.md
  examples/puma/encrypted_puma_keypair.pem
  examples/puma/key_password_command.sh
  ext/puma_http11/mini_ssl.c
  lib/puma/dsl.rb
  lib/puma/minissl.rb
  lib/puma/minissl/context_builder.rb
  test/test_integration_ssl.rb
  test/test_minissl.rb
Labels: feature, ssl, c-ext

#3137 Fixup req form data file upload with "r\n" line endings
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: bug

#3130 CI workflows - add 2 macos-13 jobs, reduce macOS jobs, timeouts, add git ref info
  .github/workflows/github_actions_info.rb
  .github/workflows/rack2.yaml
  .github/workflows/tests.yaml
Labels: CI / Testing
