Repository puma/puma, pull requests merged in 2023-06, with the labels that each got.

#3165 update URLMap Regexp usage for Ruby v3.3
  lib/puma/rack/urlmap.rb
  test/test_url_map.rb
  test/url_map_test/Gemfile
  test/url_map_test/config.ru
Labels: bug

#3174 support full certificate chain PEM for `cert_pem:` parameter to `ssl_bind`
  examples/puma/chain_cert/ca.crt
  examples/puma/chain_cert/ca.key
  examples/puma/chain_cert/ca_chain.pem
  examples/puma/chain_cert/cert.crt
  examples/puma/chain_cert/cert.key
  examples/puma/chain_cert/cert_chain.pem
  examples/puma/chain_cert/generate_chain_test.rb
  examples/puma/chain_cert/intermediate.crt
  examples/puma/chain_cert/intermediate.key
  ext/puma_http11/mini_ssl.c
  lib/puma/dsl.rb
  test/test_example_cert_expiration.rb
  test/test_puma_server_ssl.rb
Labels: bug, ssl

#3181 Fix using control server with IPv6 host
  lib/puma/binder.rb
  lib/puma/control_cli.rb
  test/helper.rb
  test/test_pumactl.rb
Labels: bug

#3187 control_cli.rb - add `require_relative 'log_writer'`
  lib/puma/control_cli.rb
  test/helpers/integration.rb
  test/test_integration_pumactl.rb
Labels: bug

#3189 README.md - clarify use of localhost gem [ci skip]
  README.md
Labels: docs
