Repository puma/puma, pull requests merged in 2023-03, with the labels that each got.

#3089 Warn when clustered-only hooks are defined in single mode
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  test/test_config.rb
Labels: feature

#3074 commonlogger.rb - fix HIJACK time format, use constants, not strings
  lib/puma/commonlogger.rb
Labels: bug

#3095 Update README and add a link to puma-daemon gem [skip ci]
  README.md
Labels: docs

#3098 [CI] test_rack_server.rb - fix rack/chunked code
  test/test_rack_server.rb
Labels: CI / Testing

#3091 Loggers - internal_write - catch Errno::EINVAL
  lib/puma/error_logger.rb
  lib/puma/log_writer.rb
Labels: bug

#2770 Custom logger
  lib/puma/dsl.rb
  lib/puma/launcher.rb
  lib/puma/log_writer.rb
  test/config/custom_logger.rb
  test/test_config.rb
Labels: feature, contrib-wanted, waiting-for-review

#3111 Fix warn_if_in_single_mode incorrect message
  lib/puma/dsl.rb
Labels: bug

#3113 Always write io_buffer when in "enum bodies" branch.
  lib/puma/request.rb
  test/test_puma_server.rb
Labels: bug

#3109 fix java 8 compatibility
  Gemfile
  Rakefile
Labels: bug, jruby, waiting-for-review
