Repository puma/puma, pull requests merged in 2024-11, with the labels that each got.

#3537 [CI] test_launcher.rb - fixup
  test/test_launcher.rb
Labels: CI / Testing

#3439 Set the worker process count automatically with WEB_CONCURRENCY=auto
  README.md
  lib/puma/configuration.rb
  test/helpers/integration.rb
  test/test_web_concurrency_auto.rb
  test/test_worker_gem_independence.rb
  test/web_concurrency_test/Gemfile
  test/web_concurrency_test/config.ru
Labels: feature

#3407 Print RUBY_DESCRIPTION when Puma starts
  lib/puma/runner.rb
Labels: feature

#3545 CI: fixup test/test_web_concurrency_auto.rb
  Gemfile
  test/helpers/integration.rb
  test/test_web_concurrency_auto.rb
  test/web_concurrency_test/Gemfile
  test/web_concurrency_test/config.ru
Labels: CI / Testing

#3335 [CI] test_puma_server.rb - update & add tests for back-to-back requests
  test/test_puma_server.rb
Labels: refactor, CI / Testing

#3525 [CI] test_puma_server.rb - add HTTP/1.0 & HTTP/1.1 checks thru to app env
  test/test_puma_server.rb
Labels: CI / Testing

#3543 Delete unnecessary task
  Rakefile
Labels: waiting-for-changes, CI / Testing

#3549 CI: fix TestIntegration#server_gets - until, not unless
  test/helpers/integration.rb
Labels: CI / Testing

#3518 Make HTTP length constants configurable for JRuby
  docs/java_options.md
  ext/puma_http11/org/jruby/puma/Http11.java
  test/test_http11.rb
Labels: jruby, waiting-for-review

#3539 Handle blank environment variables when loading config
  lib/puma/configuration.rb
  test/test_config.rb
Labels: bug

#3553 CI: test/test_request_invalid.rb - use TestPuma::PumaSocket, RFC 9112
  test/test_request_invalid.rb
Labels: CI / Testing

#3548 Request body - increase read size to 64 kB
  lib/puma/client.rb
  lib/puma/const.rb
Labels: perf, refactor

#3384 Avoid spawning `Threadpool#trim` thread if pool size is fixed
  lib/puma/server.rb
  test/test_puma_server.rb
Labels: feature, waiting-for-review

#3348 Allow alternative schemes in Binder
  docs/plugins.md
  lib/puma/binder.rb
  test/test_binder.rb
Labels: feature, waiting-for-review, plugins

#3375 Add a debug log before running each type of hook
  lib/puma/configuration.rb
  test/test_integration_cluster.rb
Labels: feature, waiting-for-review

#3376 Update DSL hook processing logic to be consistent
  lib/puma/dsl.rb
  test/test_config.rb
Labels: waiting-for-changes, refactor

#3561 CI: test/test_puma_server.rb - fixup auto_trim tests
  test/test_puma_server.rb
Labels: waiting-for-review, CI / Testing

#3562 CI: test/runner - add `-w` and `z` options for test file warnings
  test/runner
Labels: waiting-for-review, CI / Testing

#3560 Address some warnings in tests
  test/test_binder.rb
  test/test_request_invalid.rb
  test/test_web_concurrency_auto.rb
Labels: waiting-for-review

#3517 Add busy threads stat
  docs/stats.md
  lib/puma/cluster/worker.rb
  lib/puma/cluster/worker_handle.rb
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/test_cli.rb
  test/test_integration_pumactl.rb
Labels: feature, waiting-for-merge

#3528 [CI] Update stats tests
  test/helpers/integration.rb
  test/helpers/test_puma/assertions.rb
  test/test_cli.rb
  test/test_integration_pumactl.rb
Labels: waiting-for-review, CI / Testing

#3386 Add after_refork hook
  README.md
  docs/fork_worker.md
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/dsl.rb
  test/test_integration_cluster.rb
Labels: feature, waiting-for-review

#3565 Fixup use of Puma::Const::PipeRequest constants
  lib/puma/cluster.rb
  lib/puma/cluster/worker.rb
  lib/puma/const.rb
  lib/puma/runner.rb
  lib/puma/server.rb
Labels: refactor, waiting-for-merge

#3566 CI: fixup temp dir used in CI
  test/helper.rb
  test/helpers/integration.rb
Labels: waiting-for-review, CI / Testing

#3564 Add benchmark hey files and md description [ci skip]
  benchmarks/local/bench_base.rb
  benchmarks/local/bench_base.sh
  benchmarks/local/long_tail_hey.md
  benchmarks/local/long_tail_hey.rb
  benchmarks/local/long_tail_hey.sh
  benchmarks/local/response_time_wrk.rb
Labels: waiting-for-review, CI / Testing

#3383 Shorten `ThreadPool` trimmer and reaper thread names
  lib/puma/thread_pool.rb
Labels: feature, waiting-for-review

#3557 CI: refactor restart_does_not_drop_connections code
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_integration_single.rb
Labels: waiting-for-review, CI / Testing
