Repository puma/puma, pull requests merged in 2024-10, with the labels that each got.

#3508 add support in rack handler & fix regression in binder for linux abstract namespace sockets
  lib/puma/binder.rb
  lib/rack/handler/puma.rb
  test/test_rack_handler.rb
Labels: bug

#3509 [CI] tests.yml - add three macos-15 jobs - 3.1, 3.3, head
  .github/workflows/tests.yml
Labels: CI / Testing

#3510 rack/handler/puma.rb - ssl - use `start_with?`, add test
  lib/rack/handler/puma.rb
  test/test_rack_handler.rb
Labels: refactor, CI / Testing

#3468 Implement NullIO#seek and #pos to mimic IO
  lib/puma/null_io.rb
  test/test_null_io.rb
Labels: bug

#3519 [CI] - fix up test_null_io.rb TruffleRuby failure
  test/test_null_io.rb
Labels: CI / Testing

#3521 CI: Use random port in `test_on_booted`
  test/test_rack_handler.rb
Labels: CI / Testing

#3522 [CI] test_persistent.rb - fix intermittent fail in test_no_chunked_in_http10
  test/test_persistent.rb
Labels: CI / Testing

#3214 null_io.rb - add external_encoding, set_encoding, binmode, binmode?
  lib/puma/null_io.rb
  test/test_null_io.rb
Labels: bug

#3325 Single mode skip wait_for_less_busy_worker
  lib/puma/server.rb
  test/helper.rb
  test/test_busy_worker.rb
Labels: perf, waiting-for-review, refactor

#3530 [CI] fix #3325, needs method rename
  test/test_busy_worker.rb
Labels: CI / Testing

#3532 lib/rack/handler/puma.rb - fix for rackup v1.0.1, adjust Gemfile
  Gemfile
  lib/rack/handler/puma.rb
  test/test_rack_handler.rb
Labels: bug
