Repository puma/puma, pull requests merged in 2024-12, with the labels that each got.

#3575 Remove extra whitespace in single mode hook warning
  lib/puma/dsl.rb
Labels: waiting-for-review

#3581 CI: Temp fix for https://github.com/ruby/setup-ruby/pull/676
  .github/workflows/tests.yml
Labels: waiting-for-review

#3583 Revert "CI: Temp fix for https://github.com/ruby/setup-ruby/pull/676 (#3581)"
  .github/workflows/tests.yml
Labels: CI / Testing

#3584 CI: test/runner - fix test/runner:92: warning: syswrite for buffered IO
  test/runner
Labels: CI / Testing, waiting-for-merge

#3585 Add Ruby 3.4 to CI
  .github/workflows/rack_conform.yml
  .github/workflows/tests.yml
  .github/workflows/turbo-rails.yml
Labels: waiting-for-review

#3570 Option to turn off SIGUSR2 trapping
  docs/java_options.md
  lib/puma/launcher.rb
  test/test_skip_sigusr2.rb
Labels: waiting-for-review

#3591 CI: Add Windows Ruby 3.4
  .github/workflows/tests.yml
Labels: CI / Testing
