Repository puma/puma, pull requests merged in 2024-09, with the labels that each got.

#3471 [CI] test_integration_cluster.rb - remove blocking @server.gets
  test/test_integration_cluster.rb
Labels: CI / Testing

#3455 [CI] test_preserve_bundler_env.rb - Replace IO.popen with cli_server
  test/helpers/integration.rb
  test/test_preserve_bundler_env.rb
Labels: CI / Testing

#3464 [CI] Fix up test_integration_ssl.rb - use cli_server, refactor
  test/test_integration_ssl.rb
Labels: CI / Testing

#3463 []CI] Fix up test_puma_server_ssl.rb - protocol rejection and log_writer setup
  test/test_puma_server_ssl.rb
Labels: CI / Testing

#3472 [CI] test_plugin_systemd.rb - CI systems may log STATUS messages
  test/test_plugin_systemd.rb
Labels: CI / Testing

#3473 [CI] Move TestCLI clustered stats test to TestIntegrationPumactl file
  test/test_cli.rb
  test/test_integration_pumactl.rb
Labels: CI / Testing

#3492 CI: bump turbo-rails browser timeouts
  .github/workflows/turbo-rails.yml
Labels: CI / Testing

#3493 CI: remove turbo-rails ruby 2.7 job, does not work
  .github/workflows/turbo-rails.yml
Labels: CI / Testing

#3435 [doc] Mention worker index in on_worker_shutdown docs
  lib/puma/dsl.rb
Labels: docs

#3434 [doc] control_cli.rb: Harmonize help message for -Q with bin/puma [ci skip]
  lib/puma/control_cli.rb
Labels: docs

#3497 [CI] test/rackup/sleep*.ru - allow float values
  test/rackup/sleep.ru
  test/rackup/sleep_pid.ru
  test/rackup/sleep_step.ru
Labels: CI / Testing

#3498 [CI] test/rackup/sleep.ru - remove accidentally commit debug line
  test/rackup/sleep.ru
Labels: CI / Testing

#3491 Always use latest `rake-compiler`
  Gemfile
Labels: jruby, CI / Testing

#3485 Add parameters to Puma methods to allow CI to change ENV in isolation
  lib/puma/binder.rb
  lib/puma/cli.rb
  lib/puma/configuration.rb
  lib/puma/control_cli.rb
  lib/puma/error_logger.rb
  lib/puma/launcher.rb
  lib/puma/log_writer.rb
Labels: feature, CI / Testing

#3474 [CI] - test_busy_worker.rb - use TestPuma::PumaSocket
  test/helpers/test_puma/puma_socket.rb
  test/test_busy_worker.rb
Labels: CI / Testing

#3475 [CI] test_persistent.rb - use TestPuma::PumaSocket
  test/helpers/test_puma/puma_socket.rb
  test/test_persistent.rb
Labels: CI / Testing

#3462 [CI] test/test_launcher.rb - fixups
  test/test_launcher.rb
Labels: CI / Testing

#3467 Fixup jruby_restart.rb & launcher.rb to work with ARM64 macOS JRuby
  .github/workflows/tests.yml
  lib/puma/jruby_restart.rb
  lib/puma/launcher.rb
Labels: jruby

#3499 [CI] test_launcher.rb - fixup test_puma_stats_clustered, small refactor
  test/test_launcher.rb
Labels: CI / Testing

#3496 Add opt to enable keep-alives
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/request.rb
  lib/puma/server.rb
  test/test_config.rb
  test/test_puma_server.rb
Labels: feature

#3486 Mark as ractor-safe
  ext/puma_http11/puma_http11.c
Labels: feature, c-ext
