Repository puma/puma, pull requests merged in 2024-06, with the labels that each got.

#3403 CI: disable `concurrent_skipping` for skip-duplicate-actions
  .github/workflows/skip_duplicate_workflow_runs.yml
Labels: CI / Testing

#3388 [CI] tests.yml - add Ubuntu 24.04, test Ruby 3.1 thru head
  .github/workflows/tests.yml
Labels: CI / Testing

#3404 Headers must not be frozen.
  test/rackup/hello.ru
Labels: CI / Testing

#3158 [CI] test_integration_ssl_session.rb - wait for session callback
  test/test_integration_ssl_session.rb
Labels: CI / Testing

#3296 lib/client.rb - use Tempfile.create instead of Tempfile.new for request bodies
  lib/puma/client.rb
  lib/puma/request.rb
  test/test_puma_server.rb
Labels: bug

#3411 Define the on_stopped method in Puma::DSL
  lib/puma/dsl.rb
  test/config/event_on_booted.rb
  test/config/event_on_booted_and_on_stopped.rb
  test/test_integration_cluster.rb
  test/test_integration_single.rb
Labels: bug, waiting-for-review

#3416 [CI] rack_conform.yml - change Ruby 2.7 job to 3.1
  .github/workflows/rack_conform.yml
Labels: CI / Testing
