Repository puma/puma, pull requests merged in 2024-04, with the labels that each got.

#3366 [CI] Add macOS 14, remove 11, adjust so tests.yml runs 15 macOS jobs
  .github/workflows/tests.yml
Labels: CI / Testing

#3338 client.rb - fix request chunked body handling
  lib/puma/client.rb
  test/test_puma_server.rb
Labels: bug

#3359 Add `ssl_ciphersuites` option for TLSv1.3 ciphers
  README.md
  ext/puma_http11/extconf.rb
  ext/puma_http11/mini_ssl.c
  lib/puma/dsl.rb
  lib/puma/minissl.rb
  lib/puma/minissl/context_builder.rb
  test/test_binder.rb
  test/test_config.rb
  test/test_puma_server_ssl.rb
Labels: feature, ssl, waiting-for-review

#3370 extconf.rb - add logging for OpenSSL versions
  ext/puma_http11/extconf.rb
Labels: ssl, c-ext, refactor

#3360 Use actual thread local for `Puma::Server.current`.
  lib/puma/server.rb
  test/test_puma_server_current.rb
Labels: bug, waiting-for-review
