Repository puma/puma, pull requests merged in 2024-01, with the labels that each got.

#3281 Add comment about `NoDelay=true` in systemd docs
  docs/systemd.md
Labels: waiting-for-changes, systemd

#3314 Fix child processes not being reaped when `Process.detach` used
  lib/puma/cluster.rb
  test/config/process_detach_before_fork.rb
  test/test_integration_cluster.rb
Labels: waiting-for-review

#3308 Fix response repeated status line when request is invalid or errors are raised
  lib/puma/server.rb
  test/helper.rb
  test/helpers/test_puma/assertions.rb
  test/test_puma_server.rb
  test/test_web_server.rb
Labels: bug
