Repository puma/puma, pull requests merged in 2025-08, with the labels that each got.

#3684 CI: puma_socket.rb - fixup socket/request writes
  test/helpers/test_puma/puma_socket.rb
Labels: bug

#3640 Remove win-gem-test files and directory [ci skip]
  win_gem_test/Rakefile_wintest
  win_gem_test/package_gem.rb
  win_gem_test/puma.ps1
Labels: maintenance, waiting-for-review

#3651 ci: Add Ubuntu and Windows arm jobs
  .github/workflows/tests.yml
  lib/puma/detect.rb
  test/test_puma_server.rb
Labels: waiting-for-review, CI / Testing

#3688 ci: rack_conform.yml - Ruby 3.1 no longer supported
  .github/workflows/rack_conform.yml
Labels: CI / Testing

#3689 ci: test_integration_pumactl.rb - fix control_gc_stats for TruffleRuby head
  test/test_integration_pumactl.rb
Labels: waiting-for-review, CI / Testing

#3692 ci: tests.yml - set 'allow-failure' to false for non MRI jobs
  .github/workflows/tests.yml
Labels: waiting-for-review, CI / Testing

#3377 Raise an `ArgumentError` unless a hook is called with a block
  lib/puma/dsl.rb
  test/test_config.rb
Labels: feature, breaking change, v7, waiting-for-merge

#3140 Feature/support custom logger with request logs
  lib/puma/configuration.rb
  test/config/t4_conf.rb
  test/test_integration_single.rb
Labels: feature, breaking change, v7, waiting-for-merge

#3073 Set env['rack.hijack'] to client.method(:full_hijack) instead of client instance
  lib/puma/client.rb
  lib/puma/request.rb
Labels: refactor, breaking change, v7, waiting-for-merge

#3702 Fix handling of invalid Transfer-Encoding header errors
  lib/puma/client.rb
  test/test_request_single.rb
Labels: bug, waiting-for-review

#3101 Introduce support for fiber-per-request.
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  lib/puma/server.rb
  lib/puma/thread_pool.rb
  test/helper.rb
  test/test_fiber_local_application.rb
  test/test_fiber_storage_application.rb
  test/test_thread_pool.rb
Labels: feature, v7, waiting-for-merge

#3705 Fix the ability to focus individual tests
  lib/puma/server.rb
  test/test_log_writer.rb
Labels: waiting-for-review

#3701 runner.rb - remove `ruby_engine` method, deprecated Nov-2024
  lib/puma/runner.rb
Labels: maintenance, waiting-for-review

#3709 Dry up deprecation warnings and fix deprecation warnings when running CI.
  lib/puma.rb
  lib/puma/dsl.rb
  test/config/max_fast_inline_infinity.rb
  test/config/max_keep_alive_infinity.rb
  test/test_cli.rb
  test/test_config.rb
  test/test_puma_server.rb
Labels: waiting-for-review, refactor

#3712 [ci skip] Improve the DSL `preload_app!` doc
  lib/puma/dsl.rb
Labels: waiting-for-review

#3710 Simplify `Puma::DSL#process_hook` logic
  lib/puma/configuration.rb
  lib/puma/dsl.rb
Labels: refactor, waiting-for-merge
