Repository puma/puma, pull requests merged in 2025-05, with the labels that each got.

#3652 Update docs to show correct default value for worker_shutdown_timeout
  lib/puma/dsl.rb
Labels: waiting-for-review

#3653 Link to official Ruby documentation
  docs/signals.md
Labels: waiting-for-review

#3635 accept to_path to be nil on bodies
  lib/puma/request.rb
  test/helpers/test_puma/puma_socket.rb
  test/test_puma_server.rb
Labels: bug, waiting-for-review

#3656 ci: Fix Gemfiles for cgi removal in ruby head
  .github/workflows/turbo-rails.yml
  Gemfile
Labels: waiting-for-review, CI / Testing
