Repository puma/puma, pull requests merged in 2025-09, with the labels that each got.

#3719 Set default keepalive connections to 999
  lib/puma/configuration.rb
  lib/puma/dsl.rb
  test/test_puma_server.rb
Labels: breaking change

#3722 v7.0.0
  History.md
  lib/puma/const.rb
Labels: waiting-for-merge

#3725 Add backward compatibility aliases for Events class methods
  lib/puma/events.rb
  test/test_config.rb
  test/test_events.rb
Labels: bug, waiting-for-merge

#3728 7.0.1
  History.md
  lib/puma/const.rb
Labels: waiting-for-review

#3731 Fix Puma not booting if queue_requests disabled
  lib/puma/cluster/worker_handle.rb
  lib/puma/server.rb
  test/test_integration_cluster.rb
Labels: waiting-for-review

#3732 Optimize Puma::Request#default_server_port
  lib/puma/request.rb
Labels: waiting-for-merge

#3738 v7.0.2
  History.md
  Release.md
  lib/puma/const.rb
Labels: waiting-for-review

#3743 ci: update all ssl related files in examples/puma
  examples/puma/cert_puma.pem
  examples/puma/chain_cert/ca.crt
  examples/puma/chain_cert/ca.key
  examples/puma/chain_cert/ca_chain.pem
  examples/puma/chain_cert/cert.crt
  examples/puma/chain_cert/cert.key
  examples/puma/chain_cert/cert_chain.pem
  examples/puma/chain_cert/intermediate.crt
  examples/puma/chain_cert/intermediate.key
  examples/puma/client_certs/ca.crt
  examples/puma/client_certs/ca.key
  examples/puma/client_certs/ca_store.jks
  examples/puma/client_certs/ca_store.p12
  examples/puma/client_certs/client.crt
  examples/puma/client_certs/client.key
  examples/puma/client_certs/client_expired.crt
  examples/puma/client_certs/client_expired.key
  examples/puma/client_certs/client_unknown.crt
  examples/puma/client_certs/client_unknown.key
  examples/puma/client_certs/keystore.jks
  examples/puma/client_certs/server.crt
  examples/puma/client_certs/server.key
  examples/puma/client_certs/server.p12
  examples/puma/client_certs/unknown_ca.crt
  examples/puma/client_certs/unknown_ca.key
  examples/puma/client_certs/unknown_ca_store.p12
  examples/puma/encrypted_puma_keypair.pem
  examples/puma/keystore.jks
  examples/puma/puma_keypair.pem
  examples/puma/server.p12
Labels: waiting-for-review, CI / Testing

#3748 `Server#process_client` - add ka request to ThreadPool if readable & complete (prev sent to Reactor)
  lib/puma/server.rb
Labels: perf, waiting-for-review

#3749 Convert PUMA_PERSISTENT_TIMEOUT to an Integer
  lib/puma/configuration.rb
  test/test_config.rb
Labels: waiting-for-review

#3747 hey benchmark updates [ci skip]
  benchmarks/local/bench_base.rb
  benchmarks/local/bench_base.sh
  benchmarks/local/long_tail_hey-0-2-4-8.sh
  benchmarks/local/long_tail_hey.rb
Labels: maintenance, waiting-for-review

#3753 Fixup benchmark scripts
  benchmarks/local/bench_base.sh
  benchmarks/local/long_tail_hey-0-2-4-8.sh
  benchmarks/local/long_tail_hey.sh
  benchmarks/local/phased_hey.sh
  benchmarks/local/refork_hey.sh
  benchmarks/local/response_time_wrk.sh
  benchmarks/wrk/cpu_spin.sh
  examples/generate_all_certs
Labels: waiting-for-merge

#3746 Move sleep cluster logic to its own class
  lib/puma/cluster_accept_loop_delay.rb
  lib/puma/server.rb
  test/test_cluster_accept_loop_delay.rb
Labels: waiting-for-merge

#3742 Strip whitespace from the beginnings of header values
  ext/puma_http11/org/jruby/puma/Http11.java
  ext/puma_http11/puma_http11.c
  test/test_http11.rb
Labels: waiting-for-review

#3703 Fix SSL_shutdown error handling
  ext/puma_http11/mini_ssl.c
  lib/puma/server.rb
  test/helper.rb
  test/test_puma_server_ssl.rb
Labels: bug, waiting-for-merge

#3760 ci: test_puma_server_ssl.rb - catch error in thread
  test/test_puma_server_ssl.rb
Labels: CI / Testing

#3758 Add test/rackup/sleep_fibonacci.ru, update benchmark hey files
  benchmarks/local/bench_base.rb
  benchmarks/local/bench_base.sh
  benchmarks/local/long_tail_hey.rb
  test/rackup/sleep_fibonacci.ru
Labels: CI / Testing

#3765 Remove global side effect from test
  test/test_web_concurrency_auto.rb
Labels: waiting-for-review, refactor

#3772 Fix flappy `test/test_thread_pool.rb` tests
  test/test_thread_pool.rb
Labels: waiting-for-merge
