Repository puma/puma, pull requests merged in 2025-02, with the labels that each got.

#3610 Remove redundant signal exists guards in tests
  test/test_integration_cluster.rb
  test/test_plugin_systemd.rb
  test/test_plugin_systemd_jruby.rb
  test/test_preserve_bundler_env.rb
  test/test_skip_systemd.rb
  test/test_worker_gem_independence.rb
Labels: waiting-for-review

#3612 Fix GHA badge in README.md [ci skip]
  README.md
Labels: docs

#3611 Remove DSL version comments, note fork_worker as experimental
  lib/puma/dsl.rb
Labels: waiting-for-merge

#3586 Refactor `HttpParserError` handling, add `test/test_request_single.rb`
  ext/puma_http11/org/jruby/puma/Http11.java
  lib/puma/client.rb
  test/test_puma_server_ssl.rb
  test/test_request_invalid_multiple.rb
  test/test_request_single.rb
Labels: feature, bug, refactor, waiting-for-merge

#3613 Update 'clustered mode' references to 'cluster mode'
  History.md
  README.md
  docs/systemd.md
  lib/puma/dsl.rb
  test/helper.rb
Labels: docs, waiting-for-review

#3615 CI: test_puma_server_ssl.rb -fix for `set_minmax_proto_version` removal
  test/test_puma_server_ssl.rb
Labels: waiting-for-review, CI / Testing

#3614 Remove unused global $debugging_hold in test helper
  test/helper.rb
Labels: CI / Testing

#3572 Fix single runner stats before the server start
  lib/puma/single.rb
  test/test_launcher.rb
Labels: bug, waiting-for-review
