Repository puma/puma, pull requests merged in 2025-10, with the labels that each got.

#3780 ci: test_http11.rb - test_get_const_length - remove json require, misc
  test/test_http11.rb
Labels: waiting-for-review, CI / Testing

#3786 ci: macos-13 to macos-15-intel
  .github/workflows/tests.yml
Labels: CI / Testing

#3784 s/assert/assert_equal in tests
  test/test_integration_cluster.rb
Labels: waiting-for-review

#3776 `ClusterAcceptLoopDelay` docs and style follow-ups
  lib/puma/cluster_accept_loop_delay.rb
Labels: docs, waiting-for-review
