Repository puma/puma, pull requests merged in 2025-01, with the labels that each got.

#3590 Change `HttpParserError` to be subclass of `StandardError`
  ext/puma_http11/org/jruby/puma/Http11.java
  ext/puma_http11/puma_http11.c
  test/test_request_invalid.rb
Labels: bug, refactor, waiting-for-merge

#3592 CI: tests.yml - try MT_CPU: 2
  .github/workflows/tests.yml
Labels: waiting-for-merge

#3593 CI: test_integration_single.rb - fixup exit status tests when using JRuby
  test/helpers/integration.rb
  test/test_integration_single.rb
Labels: waiting-for-review, CI / Testing

#3577 CI: update `test_on_booted_and_on_stopped` integration tests
  test/config/event_on_booted_and_on_stopped.rb
  test/config/event_on_booted_exit.rb
  test/helpers/integration.rb
  test/test_integration_cluster.rb
  test/test_integration_single.rb
Labels: waiting-for-review, CI / Testing

#3595 Change ping to use const
  lib/puma/cluster/worker.rb
Labels: waiting-for-review

#3589 Reduce `TestIntegration#restart_does_not_drop_connections` restart frequency
  test/helpers/integration.rb
  test/test_integration_cluster.rb
Labels: waiting-for-review, CI / Testing

#3600 Gemfile - add logger for Ruby 3.5 and later
  Gemfile
Labels: waiting-for-review

#3594 CI: test_plugin_systemd.rb - fixups for intermittent retries
  lib/puma/sd_notify.rb
  test/test_plugin_systemd.rb
Labels: CI / Testing, waiting-for-merge

#3579 Add test for worker 0 ping with `SIGURG`
  test/test_integration_cluster.rb
Labels: CI / Testing, waiting-for-merge

#3505 Fix multi-delimiter split to get status app token
  lib/puma/app/status.rb
  test/test_app_status.rb
Labels: refactor, waiting-for-merge

#3604 Zenspider zenspider/minitest cleanup
  .github/workflows/tests.yml
  .rubocop.yml
  cops/tests_must_timeout.rb
  test/helper.rb
  test/helpers/integration.rb
  test/test_app_status.rb
  test/test_binder.rb
  test/test_bundle_pruner.rb
  test/test_busy_worker.rb
  test/test_cli.rb
  test/test_config.rb
  test/test_error_logger.rb
  test/test_events.rb
  test/test_example_cert_expiration.rb
  test/test_http10.rb
  test/test_iobuffer.rb
  test/test_json_serialization.rb
  test/test_launcher.rb
  test/test_log_writer.rb
  test/test_minissl.rb
  test/test_normalize.rb
  test/test_null_io.rb
  test/test_out_of_band_server.rb
  test/test_persistent.rb
  test/test_puma_localhost_authority.rb
  test/test_puma_server.rb
  test/test_puma_server_current.rb
  test/test_puma_server_hijack.rb
  test/test_puma_server_ssl.rb
  test/test_pumactl.rb
  test/test_rack_handler.rb
  test/test_rack_server.rb
  test/test_request_invalid.rb
  test/test_response_header.rb
  test/test_state_file.rb
  test/test_thread_pool.rb
  test/test_unix_socket.rb
  test/test_web_server.rb
Labels: waiting-for-review

#3605 6.6.0
  History.md
  lib/puma/const.rb
Labels: waiting-for-review

#3606 CI: test/helper.rb - place timeout checks inside Minitest capture_exceptions
  .rubocop.yml
  cops/tests_puma.rb
  test/helper.rb
  test/helpers/integration.rb
  test/test_app_status.rb
  test/test_binder.rb
  test/test_bundle_pruner.rb
  test/test_busy_worker.rb
  test/test_cli.rb
  test/test_config.rb
  test/test_error_logger.rb
  test/test_events.rb
  test/test_example_cert_expiration.rb
  test/test_http10.rb
  test/test_iobuffer.rb
  test/test_json_serialization.rb
  test/test_launcher.rb
  test/test_log_writer.rb
  test/test_minissl.rb
  test/test_normalize.rb
  test/test_null_io.rb
  test/test_out_of_band_server.rb
  test/test_persistent.rb
  test/test_puma_localhost_authority.rb
  test/test_puma_server.rb
  test/test_puma_server_current.rb
  test/test_puma_server_hijack.rb
  test/test_puma_server_ssl.rb
  test/test_pumactl.rb
  test/test_rack_handler.rb
  test/test_rack_server.rb
  test/test_request_invalid.rb
  test/test_response_header.rb
  test/test_state_file.rb
  test/test_thread_pool.rb
  test/test_unix_socket.rb
  test/test_web_server.rb
Labels: CI / Testing, waiting-for-merge

#3607 CI: test/test_request_invalid.rb - fix macOS TruffleRuby failures
  test/test_request_invalid.rb
Labels: CI / Testing

#3608 CI: integration.rb - catch Errno::EBADF in restart thread
  test/helpers/integration.rb
Labels: CI / Testing

#3601 Fix incomplete worker boot state on refork
  lib/puma/cluster.rb
  test/test_integration_cluster.rb
Labels: bug, waiting-for-review

#3609 CI: test_launcher.rb - move `test_puma_stats_clustered` to test_integration_clustered.rb
  test/test_integration_cluster.rb
  test/test_launcher.rb
Labels: CI / Testing, waiting-for-merge

#3598 Update refork logs
  lib/puma/cluster.rb
Labels: feature, waiting-for-merge
